### ISSUE TITLE
SampleCustomEvent is never called

### ISSUE THREAD

**Issue by oded-regev** [googleads/googleads-mobile-android-mediation#1]
Hi,

I'm trying to understand how the "Custom Events" mechanism is working via this project. The problem I'm currently facing is that the Class "SampleCustomEvent" is never called, non of the following method is ever called:

1) requestBannerAd...
2) requestInterstitialAd....
3) requestNativeAd....

Also, all the ads shown in the sample app are "test ads" from AdMob, I didn't see any ad from "Sample" network.

Can you please advise?

Thanks

**Comment by oded-regev** [comment]
Just to add some more info, the AdLoader in the MainActivity keeps getting onAdFailedToLoad() with error code: ERROR_CODE_INTERNAL_ERROR

**Comment by ericleich** [comment]
Hi there,

So sorry it's taken this long to respond.

The example app in the repo has specific ad unit IDs [here](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/Example/app/src/main/res/values/strings.xml) that are from a test account. Those ad units are configured for mediation with the preferred network being the custom event. The custom event settings have the class name as the specific class in the project for the appropriate format. When the Mobile Ads SDK makes an ad request for that ad unit, it should be getting back a mediation response with the first network being that custom event. The class name specified in the front-end should get instantiated, and the requestBannerAd (or similar method) should be called from that class.

If you're getting AdMob ads, that must mean either the ad unit configuration is messed up or the app you're running doesn't have the custom event classes included. If this is still a problem, let us know and we can investigate further. I assume you're just running the sample as is from the repo?
