### ISSUE TITLE
Request to add support for UnityAds banners

### ISSUE THREAD

**Issue by stepanov-standy** [googleads/googleads-mobile-android-mediation#103]
Hi Team,

I see that you have released UnityAds adapter with 3.0.0 support, but it doesn't have banners support that was introduced in 3.0.0 release. Please add support for banners.

**Comment by stepanov-standy** [comment]
@spilaka I see that UnityAds team has provided a pull request with banner support, it was merged to the repo, cool. When do you plan to release new Unity adapter artifact with banners support?

**Comment by spilaka** [comment]
@stepanov-standy UnityAds banner support is still under review. It is not merged yet. Mostly by the early next week we will be supporting banners. We will let you know, once we added banner support. Thank you.
