### ISSUE TITLE
FAN adapter should verify validity of ads.

### ISSUE THREAD

**Issue by clevsh** [googleads/googleads-mobile-android-mediation#121]
Hi.

Adapter of Facebook Audience Network should verify validity of the ads mediated.

If not, there is a possibility that non-chargable ads is delivered and shown.

For example,

@Override
public void onAdLoaded(Ad ad) {
    if (ad != mNativeAd) {
        Log.w(TAG, "Ad loaded is not a native ad.");
        FacebookAdapter.this.mNativeListener.onAdFailedToLoad(
                FacebookAdapter.this, AdRequest.ERROR_CODE_INTERNAL_ERROR);
                return;
     }

     // ..........
}

should be changed into...

@Override
public void onAdLoaded(Ad ad) {
    if (ad != mNativeAd) {
        Log.w(TAG, "Ad loaded is not a native ad.");
        FacebookAdapter.this.mNativeListener.onAdFailedToLoad(
                FacebookAdapter.this, AdRequest.ERROR_CODE_INTERNAL_ERROR);
                return;
     }

     if ( ad.isAdInvalidated() ) {
         Log.w(TAG, "Ad is invaild.");
        FacebookAdapter.this.mNativeListener.onAdFailedToLoad(
                FacebookAdapter.this, AdRequest.ERROR_CODE_INTERNAL_ERROR);
                return;
     }
    
     // ..........
}

All ad units (Banner, Interstitial, Navite, Rewarded Video) should be changed.

In the case of interstitial ad, it should be added to showInterstitial() function also.

@Override
    public void showInterstitial() {
        if (mInterstitialAd.isAdLoaded() && !mInterstitialAd.isAdInvalidated()) {
            mInterstitialAd.show();
        }
    }

Best Regards,
Sunho

-------------

public boolean isAdInvalidated()

Description copied from interface: Ad
Indicate whether the ad is still valid.

Specified by:
isAdInvalidated in interface Ad

Returns:
true if the ad is not valid anymore.
 
https://developers.facebook.com/docs/audience-network/reference/android/com/facebook/ads/nativeadbase.html/#isadinvalidated--

---------------------------------

**Comment by spilaka** [comment]
Acknowledged and will update the adapter in the next release. Thanks for sharing this.
