### ISSUE TITLE
FacebookAdapter.requestNativeAd() should handle isUnifiedNativeAdRequested() case

### ISSUE THREAD

**Issue by samlu** [googleads/googleads-mobile-android-mediation#143]
In FacebookAdapter.requestNativeAd(), it only call the follow code to ensure both app install and content ads are requested.
```
if (!(mediationAdRequest.isAppInstallAdRequested()
    && mediationAdRequest.isContentAdRequested())) {
```
What if caller only request unified native ads?
Should it also check ```mediationAdRequest.isUnifiedNativeAdRequested()``` case?

**Comment by spilaka** [comment]
The adapter has a code(https://github.com/googleads/googleads-mobile-android-mediation/blob/44f2dece27e4b5e1bd1a16d57d9b16b5efd57d06/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java#L468) to check isunifiedNativeAd.

**Comment by samlu** [comment]
What I was talking about is the following code:

#245 ~ #255 in requestNativeAd() function body.
> // Verify that the request is for both app install and content ads.
>         if (!(mediationAdRequest.isAppInstallAdRequested()
>                 && mediationAdRequest.isContentAdRequested())) {
>             Log.w(TAG, "Failed to request native ad. Both app install and content ad should be "
>                     + "requested");
>             mNativeListener.onAdFailedToLoad(this, AdRequest.ERROR_CODE_INVALID_REQUEST);
>             return;
>         }

**Comment by spilaka** [comment]
Acknowledged. Will update the adapter with isUnifiedAd check for the next facebook adapter release.

**Comment by samlu** [comment]
I don't see any changed code for this issue. Would you attach the changed file/line for this?

**Comment by spilaka** [comment]
@samlu There is no change in this release , we will update the adapter with that fix in next release. Thank you.
