### ISSUE TITLE
Cannot find EMPTY_LOCAL_AD_LIST in ChartboostAdapter.java in chartboost-6.6.3.0.jar.

### ISSUE THREAD

**Issue by sarpotdarsaurabh** [googleads/googleads-mobile-android-mediation#15]
Hello,
I am trying to implement chartboost as ad source along with existing adMob adunit. I downloaded and put the chartboost jar file in libs folder of my app. But when I try to generate a signed apk it gives me error/warning that EMPTY_LOCAL_AD_LIST cannot be found.  I have checked this by checking the code for ChartboostAdapter.java file present inside same jar's class files.

**Comment by sbagadi** [comment]
Hi @sarpotdarsaurabh ,

The latest version of the Chartboost SDK (7.0.0) has some changes that are incompatible with the adapter versions 6.6.3.0 or older. A [new version of the adapter](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/chartboost/CHANGELOG.md#7000) has been released which fixes the issue. You can get the latest version of the adapter from [Bintray](https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.chartboost/7.0.0.0).
