### ISSUE TITLE
Import the MoPub SDK and adapter

### ISSUE THREAD

**Issue by TheKrushik** [googleads/googleads-mobile-android-mediation#162]
Integrating MoPub with AdMob Mediation, I am doing this guide. step 3:
https://developers.google.com/admob/android/mediation/mopub

After adding repositories to the build.gradle file (Module: app):
> repositories {
>     maven { url "https://s3.amazonaws.com/moat-sdk-builds" }
> }

I get the following errors:

> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebug/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionDebugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.0, 16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionRelease/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionReleaseUnitTest/compileClasspath': Could not resolve com.google.firebase:firebase-messaging:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app
> 
> 
> ERROR: Unable to resolve dependency for ':app@productionReleaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[10.2.1, 12.1.0).
> Show Details
> Affected Modules: app

**Comment by spilaka** [comment]
@TheKrushik If you were using Android Studio, try doing this File-> Invalidate Caches/Restart. One more thing in top- level build.gradle. Add google() ahead of jcenter(). Hope this resolves issue.

**Comment by TheKrushik** [comment]
@spilaka 
It did not help. Moreover, it is reproduced on different computers.

**Comment by spilaka** [comment]
It is not an issue with AdMob SDK. The issue is your IDE is not pulling those dependencies. I was unable to replicate this issue on my end.

**Comment by TheKrushik** [comment]
https://github.com/mopub/mopub-android-sdk/issues/341
