### ISSUE TITLE
FacebookAdapter.untrackView(View view) seems to have wrong if statement?

### ISSUE THREAD

**Issue by victor-reyes** [googleads/googleads-mobile-android-mediation#165]
https://github.com/googleads/googleads-mobile-android-mediation/blob/2055fac59014fd9d7e00e42ec61b5017a92af77d/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java#L1014

```
            if (isNativeBanner) {
                mNativeAd.unregisterView();                <------- should't this be mNativeBannerAd,
            } else {
                mNativeBannerAd.unregisterView();     <------- and this be mNativeAd?
            }
        }
```

I get the following error:
> java.lang.NullPointerException: Attempt to invoke virtual method 'void com.facebook.ads.NativeAd.unregisterView()' on a null object reference
>         at com.google.ads.mediation.facebook.FacebookAdapter$UnifiedAdMapper.untrackView(FacebookAdapter.java:1308)

**Comment by spilaka** [comment]
Fixed in  adapter 5.4.1.1. FAN Adapter 5.4.1.1 is live.
