### ISSUE TITLE
Facebook adapter: forget to call mRewardedVideoAd.destroy() in onDestroy()?

### ISSUE THREAD

**Issue by samlu** [googleads/googleads-mobile-android-mediation#17]
I can see that this adapter calls mInterstitialAd.destroy() and mNativeAd.unregisterView() functions in FacebookAdapater.onDestroy().

Should it also call mRewardedVideoAd.destroy() in onDestroy()?

**Comment by ericleich** [comment]
Looks like it, assigning to @sbagadi to take a closer look.

**Comment by sbagadi** [comment]
Updated the adapter to call [`destroy()`](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java#L159).
