### ISSUE TITLE
FAN: should update the required Google Mobile Ads SDK version to 18.2.0

### ISSUE THREAD

**Issue by samlu** [googleads/googleads-mobile-android-mediation#179]
In Facebook Android Mediation Adapter 5.5.0.0, it will call `MediationBannerAdConfiguration.getWatermark()` in some classes. E.g.

```
public final class FacebookRtbBannerAd implements MediationBannerAd, AdListener {
  private MediationBannerAdConfiguration adConfiguration;
  public void render() {
    ...
    if (!TextUtils.isEmpty(adConfiguration.getWatermark())) {
}
```

`MediationBannerAdConfiguration.getWatermark()` only exists in Google Mobile Ads SDK version in 18.2.0 or above, so you have to update the minimum required Google Mobile Ads SDK version to 18.2.0.

In **ThirdPartyAdapters/facebook/facebook/build.gradle** file, it should change 18.1.1 to 18.2.0 as below:
implementation 'com.google.android.gms:play-services-ads:**18.2.0**'

**Comment by spilaka** [comment]
@samlu Thanks for that. Fixed.
