### ISSUE TITLE
Facebook Native ad mediation can not click

### ISSUE THREAD

**Issue by memorycj** [googleads/googleads-mobile-android-mediation#193]
mediation SDK Version : 5.6.0.0
play-services-ads SDK Version : 18.3.0

I noticed that you guys have fixed this problem, but I still have problems with the latest version of the SDK here. What should I do to solve this?

Observe logcat found no valuable logs

**Comment by memorycj** [comment]
find log ：

com.facebook.ads.NativeAdBase$Image@14b763a with size [144x144]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.lang.NullPointerException(Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{StringUri->Object->Drawable}, LOCAL
    There was 1 cause:
    java.lang.NullPointerException(Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Drawable->Drawable}
    There was 1 cause:
    java.lang.NullPointerException(Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        Cause (2 of 2): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{StringUri->Bitmap->Drawable}

**Comment by stepanov-standy** [comment]
Google Team, was this fixed? I see 5.6.1.0 version, but according to change log in Facebook folder there were no fixes for this problem.

**Comment by neobie** [comment]
Hi, I am also having such problem. From Facebook dashboard, there are impressions and filled, but no clicks.
Today, I tested and confirm that I can't click native ad. Nothing happen.
But adchoice is clickable.

**Comment by joshuajplagonera** [comment]
Hi All,
Are you still able to experience this issue? I tried with the latest version of the FAN adapter and I am not experiencing this issue on my end.

**Comment by memorycj** [comment]
Thanks for the reply, this problem has been fixed, the reason is that I use the setNativeBanner api wrongly here
