### ISSUE TITLE
Multiple Account Ids

### ISSUE THREAD

**Issue by rorodevelop** [googleads/googleads-mobile-android-mediation#210]
This is more an AdMob Problem in my case.
In the AdMob mediation configuration, I set the account ID wrong on one Ad for InMobi. The result is, even after correcting, the incorrect and the correct id remain on the server.

If there are more than one ids, the sdk is set up in a way that it always takes the first id, which is wrong in my case:

2020-02-01 21:32:29.467 14207-14207/com.***.**** W/InMobiMediationAdapter: Multiple 'accountid' entries found: [15**************, 63cc325*************]. Using '15**************' to initialize the InMobi SDK

I would propose to add a way to change the account id. Thanks.

**Comment by rorodevelop** [comment]
Update: After waiting a day, it works. So my problem is solved.

**Comment by Eswateam** [comment]
Hi,
How did you solve this issue, I have 2 appId for my network and I always get the same warning even my admob mediation group link to only one appId at a time

**Comment by rorodevelop** [comment]
Hi,

After waiting a day, the incorrect ID was removed.

Regards,
Rolf

Eswateam <notifications@github.com> schrieb am Mi., 4. März 2020, 18:08:

**Comment by Eswateam** [comment]
oh okay thanks. My issue is quite different, I have two app ID but the mediation adapter always initialize the first one.

**Comment by rorodevelop** [comment]
Hi,

Unfortunately, the Google Team is not very responsive....

Eswateam <notifications@github.com> schrieb am Mi., 4. März 2020, 18:41:

**Comment by Eswateam** [comment]
Yeah I tried also many forum without any answer.

**Comment by joshuajplagonera** [comment]
Hi All,
It is intended behavior that the adapter will only try to initialize the inMobi SDK using only a single account ID. That said, we recommend that you remove any other account IDs from your mediation configurations.

**Comment by Eswateam** [comment]
Hi,
Yes this is normal inMobi and other sdk use a single Id to initialize.
But for example for a kids game you need to have 2 accounts ID (one ID for COPPA players and other one for non COPPA players). Then with this setup the mediation no longer work as the mediation adapter detect 2 ID and select the first one to initialize.

**Comment by joshuajplagonera** [comment]
HI @Eswateam 
Unfortunately, this is not supported by the InMobi adapter since the InMobi SDK can only be initialized using one InMobi account ID.

**Comment by Eswateam** [comment]
I meant no accountID but appID.
What if a game have an age gate, you need two app ID to be compliant with legislation right ?

**Comment by ericleich** [comment]
We recommend reaching out to InMobi regarding their best practices to be compliant with certain regulations.

Note that appID is a deprecated concept on the InMobi side. Per https://developers.google.com/admob/android/mediation/inmobi#step_2_configure_mediation_settings_for_your_ad_unit, you only need to pass in Account ID and placement ID. These are also the only two fields the adapter is looking at.

**Comment by ericleich** [comment]
If InMobi's age gate settings are app level, you should be able to a single account ID for all ad units, and set up 2 different InMobi apps in their UI, each with their own placement. Then you just provide the AdMob UI the placement ID that you want to use. In this way, all of your InMobi mediation group settings in the AdMob UI use the same account ID.
