### ISSUE TITLE
Vungle SDK 6.5.2

### ISSUE THREAD

**Issue by neobie** [googleads/googleads-mobile-android-mediation#228]
I have been seeing Vungle Android/iOS SDK version 6.5.2 has been update for quite a long time, but the mediation adapter hasn't up to date yet.

**Comment by ericleich** [comment]
Hi there, there are open pull requests in this repo to get the adapter updated, but we're still working on certifying the integration. Vungle is adding support for banner formats that aren't 300x250.

**Comment by ericleich** [comment]
https://github.com/googleads/googleads-mobile-android-mediation/pull/212 got merged and Vungle adapter 6.5.3.0 has been released
