### ISSUE TITLE
InMobi 9.0.6.0 not uploaded properly on bintray

### ISSUE THREAD

**Issue by RajSuvariya-InMobi** [googleads/googleads-mobile-android-mediation#251]
@joshuajplagonera The latest InMobi adapter(#248) is not released properly on the bintray. I can't find any jars under files on https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.inmobi/9.0.6.0#

Can you please quickly resolve the bintray issue?

**Comment by RajSuvariya-InMobi** [comment]
Also when I try to add the following dependency in the project 
`    implementation 'com.google.ads.mediation:inmobi:9.0.6.0'`

it fails with 

```
ERROR: Failed to resolve: com.google.ads.mediation:inmobi:9.0.6.0
Show in Project Structure dialog
Affected Modules: app
```

**Comment by joshuajplagonera** [comment]
Hi @RajSuvariya-InMobi 
The InMobi Android adapter version 9.0.6.0 should now be live.
