### ISSUE TITLE
MoPub adapter SSV reward issue

### ISSUE THREAD

**Issue by efryntov** [googleads/googleads-mobile-android-mediation#262]
Currently there is no way to pass custom data used in the SSV callback as described in [MoPub SDK documentation - passing custom data](https://developers.mopub.com/publishers/android/rewarded-video/#passing-custom-data)

According to the documentation for server-to-server webhook to send the data it needs to be passed like following `MoPubRewardedVideos.showRewardedVideo(String adUnitId, String customData)` but `MoPubMediationAdapter.showAd(Context context)` calls through to `MoPubSingleton.showRewardedAd(String adUnitId)` which, in turn, calls through to `MoPubRewardedVideos.showRewardedVideo(String adUnitId)` omitting the custom data argument.
https://github.com/googleads/googleads-mobile-android-mediation/blob/c91edf7972703b07e6bdd0d5597e8cc9c3d2e827/ThirdPartyAdapters/mopub/mopub/src/main/java/com/google/ads/mediation/mopub/MoPubSingleton.java#L59-L69

There needs to be a way to set the custom data parameter prior to calling `MoPubMediationAdapter.showAd(Context context)` which then will pass this argument all the way through to the two-argument method `MoPubRewardedVideos.showRewardedVideo(String adUnitId, String customData)`

Note that it is safe to call the two-argument `MoPubRewardedVideos.showRewardedVideo(String adUnitId, String customData)` with `customData == null` since one-argument `MoPubRewardedVideoManager.showVideo(String adUnitId)` just calls `MoPubRewardedVideoManager.showVideo(adUnitId, null)`

[MoPub source code link](https://github.com/mopub/mopub-android-sdk/blob/90521b9ce0b8ea7293ab0cbe6c13c04b55905a79/mopub-sdk/mopub-sdk-fullscreen/src/main/java/com/mopub/mobileads/MoPubRewardedVideoManager.java#L357-L366)

**Comment by joshuajplagonera** [comment]
Hi @efryntov 
Thank you for the detailed explanation. We will take a look into this and let you know once we have any updates.

**Comment by joshuajplagonera** [comment]
Hi @efryntov ,
We added new extras to the adapter that allows you to pass in custom data when showing MoPub rewarded ads as per your suggestion:
https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/mopub/CHANGELOG.md
