### ISSUE TITLE
Does AppLovin need ActivityContext?

### ISSUE THREAD

**Issue by 1008k** [googleads/googleads-mobile-android-mediation#280]
The AppLovin adapter throws an error when making an ad using the ApplicationContext.
This is because the adapter requests the ActivityContext with this code.

[AdMob>AppLovin Adapter](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/ApplovinAdapter.java)
```
if (!(context instanceof Activity)) {
...
return;
}
```

On the other hand, the MoPub adapter also allows ApplicationContext for certain versions and above.

[MoPub>Applovin Adapter](https://github.com/mopub/mopub-android-mediation/blob/master/AppLovin/src/main/java/com/mopub/mobileads/AppLovinBanner.java)
```
// SDK versions BELOW 7.1.0 require a instance of an Activity to be passed in as the context
if (AppLovinSdk.VERSION_CODE < 710 && !(context instanceof Activity)) {
...
return;
}
```

If there is no problem, I would be happy if there is no restriction on Context according.

**Comment by joshuajplagonera** [comment]
Hi @1008k ,
Thank you for raising this issue to us. We will make an update to the adapter to allow the use of an `Application` context to load ads.
Additionally, please note that each adapter is built and tested against a specific version of the AppLovin SDK.

That said, please be aware that, as per our [Best Practices](https://developers.google.com/admob/android/mediate#initialize_your_ad_object_with_an_activity_instance), it is still recommended to load ads using an Activity context.

**Comment by joshuajplagonera** [comment]
Hi @1008k ,
The fix for this should now be live. You can refer to the [CHANGELOG for the AppLovin adapter](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/applovin/CHANGELOG.md#version-91440) for more information.
