### ISSUE TITLE
Admob Facebook Mediation leaked IntentReceiver

### ISSUE THREAD

**Issue by karopass** [googleads/googleads-mobile-android-mediation#29]
I have implemented Facebook mediation in my android application as guide. Its working fine and I am getting ads also. I have marked that its giving errors like this     

> Activity com.mypackage.myapp.activities.ActivityCustomization has  leaked IntentReceiver  com.facebook.ads.internal.DisplayAdController$c@2dad754 that was  originally registered here. Are you missing a call to  unregisterReceiver()?                                                                       android.app.IntentReceiverLeaked: Activity  com.karopass.gujarati_status.activities.ActivityCustomization has leaked  IntentReceiver com.facebook.ads.internal.DisplayAdController$c@2dad754  that was originally registered here. Are you missing a call to  unregisterReceiver()?   

As per instruction given in above link I have not added any codes in  my activities. Let me know what should additional I need to do for fix  this errors. Thanks

**Comment by spilaka** [comment]
Still are you facing the same issue ?
