### ISSUE TITLE
FacebookRtbNativeAd with empty cover

### ISSUE THREAD

**Issue by vkomysh-vicman** [googleads/googleads-mobile-android-mediation#324]
Cover image inits with empty constructor `FacebookAdapterNativeAdImage()` 
https://github.com/googleads/googleads-mobile-android-mediation/blob/37a6efdbba815c52f1a3ed4c0e5b9ed763dc4b63/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbNativeAd.java#L195

Expected implementation (like into `FacebookAdapter`)
https://github.com/googleads/googleads-mobile-android-mediation/blob/37a6efdbba815c52f1a3ed4c0e5b9ed763dc4b63/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java#L796

**Comment by joshuajplagonera** [comment]
Hi @vkomysh-vicman ,
Thank you for your report. We have submitted a recent change that should fix this in the next version: https://github.com/googleads/googleads-mobile-android-mediation/commit/96cddccc1fe1f0f838736614585e79a5e98b8ceb
