### ISSUE TITLE
Facebook Mediation not compatible with gms 19.5 (crash)

### ISSUE THREAD

**Issue by Inspyro** [googleads/googleads-mobile-android-mediation#326]
I tried using facebook mediation with the latest google-ads for unity (has 19.5.0 as version)
According to the change logs we should use facebook ads 6.2.0.0 as they were built against gms 19.5.0, but unfortunately a conflicting dependency is detected, thus the android resolver downloads gms 20.0.0 instead. This leads the app to crash becasue facebook mediation is not compatible with gms 20.0.0

Some conflicting dependencies were found.
The following dependency versions were modified:
com.google.ads.mediation:facebook:6.2.0.0 --> com.google.ads.mediation:facebook:6+
com.google.android.gms:play-services-ads:19.5.0 --> com.google.android.gms:play-services-ads:+

How can this issue be solved?

**Comment by Inspyro** [comment]
The same issue was reported in another repository: https://github.com/googleads/googleads-mobile-unity/issues/1591

**Comment by DacNV95** [comment]
Hello, today I encountered this problem. After finding out t has determined the cause of the conflict between Facebook Audience Network v6.2.1 (requires play-service 20.0.0 to use bidding feature with admob) vs Admob v5.4.0 (requires play- service 19.5.0), while play-service 20.0.0 removed many reward functions so this error was generated.
While waiting for google to release the update to support play-service 20.0.0, you can use the following: in the build settings, check the custom build gradle (unity 2018.4) then resolve again, t used still see normal ads without errors.

**Comment by TarmoJussila** [comment]
> you can use the following: in the build settings, check the custom build gradle (unity 2018.4) then resolve again, t used still see normal ads without errors.

@DacNV95 can you specify the steps needed to setup the main gradle to support this behaviour?

**Comment by DacNV95** [comment]
https://github.com/googleads/googleads-mobile-unity/issues/1591
you can see it here
