### ISSUE TITLE
MoPub Rewarded Ad callback is lost after GC

### ISSUE THREAD

**Issue by DeweyReed** [googleads/googleads-mobile-android-mediation#344]
Because https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/mopub/mopub/src/main/java/com/google/ads/mediation/mopub/MoPubSingleton.java#L34 stores the callback in `WeakReference`, the callback can be easily lost during a GC.

Steps to reproduce:

1. Use ads 20.2.0 and MoPub mediation 5.17.0.0.
1. Set up a MoPub rewarded ad.
1. After the ad starts playing, open the memory profiler in Android Studio and force GC several times.
1. After the ad ends, the reward callback isn't fired.

**Comment by joshh-devrel** [comment]
Closed as this is obsolete - [MoPub has sunset](https://developers.google.com/admob/android/mediation/mopub).
