### ISSUE TITLE
onDestroy is not called for adapters that failed to load Ad

### ISSUE THREAD

**Issue by ogrenichv** [googleads/googleads-mobile-android-mediation#347]
`onDestroy` method of `MediationAdapter` interface is supposed to free resources allocated by an adapter. Right now it is invoked only if an Ad was successfully loaded by the adapter i.e. if the adapter invoked `MediationBannerListener.onAdLoaded` method. If the adapter for some reason wasn't able to load an Ad and invoked `MediationBannerListener.onAdFailedToLoad` method then the adapter's `onDestroy` method will never be invoked. In case the adapter allocated any resources and failed to load an Ad then those resources won't be freed.

Let us take a look at MoPub adapter. In `requestBannerAd` it creates an instance of MoPubView, which registers broadcast receiver in its constructor. MoPubView has `destroy` method which unregisters this broadcast receiver. MoPub adapter destroys the instance of MoPubView in its `onDestroy` method. I expect that `onDestroy` method will always be invoked despite the fact that the adapter failed to load an Ad. But it is not called when MoPub failed to load an Ad (no fill, bad configuration, etc.), it results in broadcast receiver leak.

**Comment by joshh-devrel** [comment]
Closed as this is obsolete - [MoPub has sunset](https://developers.google.com/admob/android/mediation/mopub).
