### ISSUE TITLE
com.google.ads.mediation:facebook:6.3.0.1 availability 

### ISSUE THREAD

**Issue by manuhook** [googleads/googleads-mobile-android-mediation#349]
Hi,

On com.google.ads.mediation:facebook, only versions 6.4.0.0 to 6.5.1.1 are available
https://maven.google.com/web/index.html?q=Facebook#com.google.ads.mediation:facebook

Can you please add 6.3.0.1, we are still using it.

Thank you,

**Comment by joshh-devrel** [comment]
Closed this issue as it's obsolete. Pub should always use the latest Meta Android adapter version as indicated in [changelog](https://developers.google.com/admob/android/mediation/meta#meta-audience-network-android-mediation-adapter-changelog).
