### ISSUE TITLE
Admob new Adapter class and MediationBannerAd interface does not have onDestroy method how to get destroy callback when using admob mediation

### ISSUE THREAD

**Issue by amodkanthe** [googleads/googleads-mobile-android-mediation#356]
using  implementation `"com.google.android.gms:play-services-ads:20.3.0"`

Following is my admob banner adapter code

```
public class MyCustomBannerAdapter extends Adapter implements MediationBannerAd {
      @Override
      public void loadBannerAd(@NonNull MediationBannerAdConfiguration mediationBannerAdConfiguration, @NonNull MediationAdLoadCallback<MediationBannerAd, MediationBannerAdCallback> callback) {
      }

}
```
Using this I am no where getting onDestroy callback which was previously provided by `com.google.android.gms.ads.mediation.customevent.CustomEventBanner`

how to get **onDestroy** callback using new admob sdk mediation

**Comment by amodkanthe** [comment]
any update?

**Comment by sanderson82** [comment]
Any update on this?

**Comment by joshh-devrel** [comment]
Thanks for creating this GitHub issue. I have brought this feedback to the internal team and there isn't any timeline on supporting it yet. You can follow the [banner custom event dev doc](https://developers.google.com/admob/android/custom-events/banner) for latest updates.
