### ISSUE TITLE
TapJoy adapter crash on android.util.Log.println_native

### ISSUE THREAD

**Issue by DenizPiri** [googleads/googleads-mobile-android-mediation#360]
We are using "com.google.ads.mediation:tapjoy:**12.8.1.0**", and getting many occurrences of  the following crash in Firebase Crashlytics:

```
Caused by java.lang.NullPointerException
println needs a message

android.util.Log.println_native (Log.java)
android.util.Log.e (Log.java:334)
com.google.ads.mediation.tapjoy.rtb.TapjoyRtbInterstitialRenderer$1$2.run (TapjoyRtbInterstitialRenderer.java:145)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:145)
android.app.ActivityThread.main (ActivityThread.java:5942)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1400)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1195)
```

I assume this commit was supposed to fix this issue: https://github.com/googleads/googleads-mobile-android-mediation/commit/339068cbe52812ca18ff173d12bc8fdad16354e2 However, it doesn't seem to be addressing the actual issue.

Each occurrence seems to be originating from **TapjoyRtbInterstitialRenderer.java:145**. I believe TapJoy's TJError.message field is null, and AdError just passes it through.

It would be great if a fix could be applied and released soon!

Thanks!

**Comment by joshh-devrel** [comment]
Hello Deniz,

Version 12.8.1.1 is now live with the fix.

Thanks!
