### ISSUE TITLE
Unity Facebook adapter 3.2.0 not ready.

### ISSUE THREAD

**Issue by adgjl002** [googleads/googleads-mobile-android-mediation#361]
I am trying to implement facebook bidding in Admob Mediation using GoogleMobileAds-native.unitypackage.

However, when MobileAds.Initialize() is called, Applovin, Admob, and AdColony adapters are normally ready, but only the Facebook adapter is not ready.

Even when I check the status through TestSuite, only Facebook's Adapter Initialization Status is not Ready.

Is there any way to solve this??

![KakaoTalk_20210923_184913061](https://user-images.githubusercontent.com/53658745/134487371-665c561a-bda6-4362-a152-ef3def9347ca.jpg)

**Comment by cavallinii** [comment]
Hi, I have Facebook Ads working correctly. I have the Google Mobile Ads plugin v6.1.2. I have added the Facebook Audience Network SDK 6.4.0 and the adapter v3.6.0. 

I also initialize the Facebook SDK in the void Awake function. 

using AudienceNetwork;
AudienceNetworkAds.Initialize();

I don't know if it is strictly necessary but it works and I get impressions with open bidding. 

One question, I don't get the mediation working with Adcolony, could you tell me what steps you have done to make it work?

Thank you very much.

**Comment by VineshChauhan24** [comment]
Simple Step to do FB mediation with Admob

Step 1: //dependancies
   //    admob
    implementation 'com.google.android.gms:play-services-ads:20.4.0'
    //facebook mediation
    implementation 'com.google.ads.mediation:facebook:6.8.0.0'

Step 2:-   MobileAds.initialize(this, new OnInitializationCompleteListener() {
  @Override
  public void onInitializationComplete(InitializationStatus initializationStatus) {

  }
});

    AdSettings.addTestDevice("ID”);//
    
    MobileAds.setRequestConfiguration(
            new RequestConfiguration.Builder().setTestDeviceIds(Arrays.asList("ID"))
                    .build());//


Note: -  USE Real Ads id and Configure your Device for Testing on Admob and Facebook Dashboard

**Comment by joshh-devrel** [comment]
Mediation test suite is sunset, please use [ad inspector](https://developers.google.com/admob/android/ad-inspector) for debugging mediation issues. Also, use the latest Meta Unity adapter instead, see [changelog](https://developers.google.com/admob/unity/mediation/meta#meta-audience-network-unity-mediation-plugin-changelog).
