### ISSUE TITLE
How to judge the completion of initialization

### ISSUE THREAD

**Issue by llllonger** [googleads/googleads-mobile-android-mediation#365]
i use RewardedAd，and the callback of OnInitializationCompleteListener is a map,the result is below:
"AdMob init key= com.google.android.gms.ads.MobileAds and value= READY
AdMob init key= com.google.ads.mediation.vungle.VungleMediationAdapter and value= NOT_READY
AdMob init key= com.google.ads.mediation.applovin.AppLovinMediationAdapter and value= NOT_READY
AdMob init key= com.google.ads.mediation.adcolony.AdColonyMediationAdapter and value= NOT_READY
AdMob init key= com.google.ads.mediation.tapjoy.TapjoyMediationAdapter and value= NOT_READY
"
i was confused 
”AdMob init key= com.google.android.gms.ads.MobileAds and value= READY“ Can this be considered as successful initialization？

**Comment by joshh-devrel** [comment]
The logging message shows that the Google Mobile Ads SDK initialized successfully, but none of the mediation adapters initialized successfully.
