### ISSUE TITLE
A resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.   0, 17.0.0]", but isn't being resolved to that version.

### ISSUE THREAD

**Issue by Luklek** [googleads/googleads-mobile-android-mediation#367]
When I try to add implementation 'com.google.ads.mediation:tapjoy:12.8.1.0' I am getting the error below (but it doesn't happen if I add only the tapjoy SDK):

Dependency resolved to an incompatible version: Dependency(fromArtifactVersion=ArtifactVersion(groupId=com.tapjoy, artifactId=tapjoy-android-sdk, version=12.8.1), toArtifact=Artifact(groupId=com.google.android.gms, artifactId=play-services-ads-identifier), toArtifactVersionString=[15.0.0, 17.0.0])
Dependency Resolution Help: Displaying all currently known paths to any version of the dependency: Artifact(groupId=com.google.android.gms, artifactId=play-services-ads-identifier)
NOTE: com.google.android.gms translated to c.g.a.g for brevity. Same for com.google.firebase -> c.g.f
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.tapjoy:tapjoy-android-sdk@{strictly 12.8.1}
---- com.tapjoy:tapjoy-android-sdk:12.8.1 library depends -> c.g.a.g:play-services-ads-identifier@[15.0.0, 17.0.0]
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:tapjoy@{strictly 12.8.1.0}
---- com.google.ads.mediation:tapjoy:12.8.1.0 library depends -> com.tapjoy:tapjoy-android-sdk@12.8.1
------ com.tapjoy:tapjoy-android-sdk:12.8.1 library depends -> c.g.a.g:play-services-ads-identifier@[15.0.0, 17.0.0]
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:tapjoy@12.8.1.0
---- com.google.ads.mediation:tapjoy:12.8.1.0 library depends -> com.tapjoy:tapjoy-android-sdk@12.8.1
------ com.tapjoy:tapjoy-android-sdk:12.8.1 library depends -> c.g.a.g:play-services-ads-identifier@[15.0.0, 17.0.0]
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-ads-identifier@{strictly 17.0.0}
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-measurement@{strictly 19.0.2}
---- c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
------ c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@{strictly 19.0.2}
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
------ c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
-------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@20.4.0
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
-------- c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
---------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@{strictly 20.4.0}
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
-------- c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
---------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@19.0.2
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
------ c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
-------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-measurement-sdk@{strictly 19.0.2}
---- c.g.a.g:play-services-measurement-sdk:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
------ c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@{strictly 19.0.2}
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-sdk@19.0.2
------ c.g.a.g:play-services-measurement-sdk:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
-------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@20.4.0
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-sdk@19.0.2
-------- c.g.a.g:play-services-measurement-sdk:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
---------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@{strictly 20.4.0}
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-sdk@19.0.2
-------- c.g.a.g:play-services-measurement-sdk:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
---------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@19.0.2
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-sdk@19.0.2
------ c.g.a.g:play-services-measurement-sdk:19.0.2 library depends -> c.g.a.g:play-services-measurement-impl@19.0.2
-------- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-measurement-impl@{strictly 19.0.2}
---- c.g.a.g:play-services-measurement-impl:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.android.ump:user-messaging-platform@{strictly 1.0.0}
---- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@20.4.0
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-lite@20.4.0
-------- c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
---------- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@{strictly 20.4.0}
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-lite@20.4.0
-------- c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
---------- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:applovin@{strictly 10.3.4.0}
---- com.google.ads.mediation:applovin:10.3.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-lite@20.4.0
-------- c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
---------- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:applovin@10.3.4.0
---- com.google.ads.mediation:applovin:10.3.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-lite@20.4.0
-------- c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
---------- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-ads@{strictly 20.4.0}
---- c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-lite@20.4.0
------ c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
-------- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:tapjoy@{strictly 12.8.1.0}
---- com.google.ads.mediation:tapjoy:12.8.1.0 library depends -> c.g.a.g:play-services-ads@20.2.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-lite@20.4.0
-------- c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
---------- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:tapjoy@12.8.1.0
---- com.google.ads.mediation:tapjoy:12.8.1.0 library depends -> c.g.a.g:play-services-ads@20.2.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-lite@20.4.0
-------- c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
---------- com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-ads-lite@{strictly 20.4.0}
---- c.g.a.g:play-services-ads-lite:20.4.0 library depends -> com.google.android.ump:user-messaging-platform@1.0.0
------ com.google.android.ump:user-messaging-platform:1.0.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@{strictly 19.0.2}
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-api@19.0.2
------ c.g.a.g:play-services-measurement-api:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@20.4.0
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-api@19.0.2
-------- c.g.a.g:play-services-measurement-api:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@{strictly 20.4.0}
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-api@19.0.2
-------- c.g.a.g:play-services-measurement-api:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@19.0.2
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement-api@19.0.2
------ c.g.a.g:play-services-measurement-api:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-measurement-api@{strictly 19.0.2}
---- c.g.a.g:play-services-measurement-api:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.applovin:applovin-sdk@{strictly 10.3.4}
---- com.applovin:applovin-sdk:10.3.4 library depends -> c.g.a.g:play-services-ads-identifier@16.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.applovin:applovin-sdk@10.3.4
---- com.applovin:applovin-sdk:10.3.4 library depends -> c.g.a.g:play-services-ads-identifier@16.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:applovin@{strictly 10.3.4.0}
---- com.google.ads.mediation:applovin:10.3.4.0 library depends -> com.applovin:applovin-sdk@10.3.4
------ com.applovin:applovin-sdk:10.3.4 library depends -> c.g.a.g:play-services-ads-identifier@16.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:applovin@10.3.4.0
---- com.google.ads.mediation:applovin:10.3.4.0 library depends -> com.applovin:applovin-sdk@10.3.4
------ com.applovin:applovin-sdk:10.3.4 library depends -> c.g.a.g:play-services-ads-identifier@16.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-measurement@{strictly 19.0.2}
---- c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@{strictly 19.0.2}
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
------ c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@20.4.0
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
-------- c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@{strictly 20.4.0}
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.f:firebase-analytics@18.0.3
------ c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
-------- c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-analytics@19.0.2
---- c.g.f:firebase-analytics:19.0.2 library depends -> c.g.a.g:play-services-measurement@19.0.2
------ c.g.a.g:play-services-measurement:19.0.2 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@20.4.0
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.f:firebase-ads@{strictly 20.4.0}
---- c.g.f:firebase-ads:20.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:applovin@{strictly 10.3.4.0}
---- com.google.ads.mediation:applovin:10.3.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:applovin@10.3.4.0
---- com.google.ads.mediation:applovin:10.3.4.0 library depends -> c.g.a.g:play-services-ads@20.4.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> c.g.a.g:play-services-ads@{strictly 20.4.0}
---- c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:tapjoy@{strictly 12.8.1.0}
---- com.google.ads.mediation:tapjoy:12.8.1.0 library depends -> c.g.a.g:play-services-ads@20.2.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
-- :app-zBow01PinkPastelDebugCompileClasspath-app:0.0.0 task/module dep -> com.google.ads.mediation:tapjoy@12.8.1.0
---- com.google.ads.mediation:tapjoy:12.8.1.0 library depends -> c.g.a.g:play-services-ads@20.2.0
------ c.g.a.g:play-services-ads:20.4.0 library depends -> c.g.a.g:play-services-ads-identifier@17.0.0
:app:processZBow01PinkPastelDebugResources (Thread[Execution worker for ':',5,main]) completed. Took 0.108 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processZBow01PinkPastelDebugResources'.
> In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.
  0, 17.0.0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

  Dependency failing: com.tapjoy:tapjoy-android-sdk:12.8.1 -> com.google.android.gms:play-services-ads-identifier@[15.0.0,
   17.0.0], but play-services-ads-identifier version was 17.0.0.

**Comment by chrisnkrueger** [comment]
I have the same issue.

**Comment by Mr-Ramzan** [comment]
any luck?

**Comment by devekaam** [comment]
Same here.

I think this issue is only for Tapjoy, so the title should include the name "Tapjoy".


This version  is OK.
    implementation 'com.google.ads.mediation:tapjoy:12.8.0.1'

but these versions cause Dependency failing.
    implementation 'com.google.ads.mediation:tapjoy:12.8.1.0'
    implementation 'com.google.ads.mediation:tapjoy:12.9.0.0'

> a resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.0, 17.1.0]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown. Dependency failing: com.tapjoy:tapjoy-android-sdk:12.9.0 -> com.google.android.gms:play-services-ads-identifier@[15.0.0, 17.1.0], but play-services-ads-identifier version was 18.0.0.

I don't know this is caused by mediation adapter or Tapjoy SDK, but this is the release note of Tapjoy SDK.
https://dev.tapjoy.com/en/android-sdk/Changelog

Does any one know how to fix this issue?

**Comment by kjakm** [comment]
Hi All,

You can exclude Tapjoy's play services dependency by adding the adapter to your project like so:

`
implementation ('com.google.ads.mediation:tapjoy:12.8.1.0') {
    exclude group: 'com.google.android.gms', module: 'play-services-ads-identifier'
}
`

If you need any further assistance from Tapjoy, you can get in touch directly via the link on [this page](https://dev.tapjoy.com/en).

Best,
Kieran

**Comment by devekaam** [comment]
Thank you! @kjakm
Oh, you are a person in TapJoy!

I hope the document below is also updated.
https://developers.google.com/admob/android/mediation/tapjoy

Or, I hope the unnecessary dependency is removed for further release. (Sorry if it's necessary.)

**Comment by joshh-devrel** [comment]
Please update to use the [latest Tapjoy Android adapter version](https://developers.google.com/admob/android/mediation/tapjoy#tapjoy-android-mediation-adapter-changelog), thanks!
