### ISSUE TITLE
Gradle Build Fail due to dependency `com.google.ads.mediation:facebook` when building on `compileSdkVersion 30`

### ISSUE THREAD

**Issue by bearhugmo** [googleads/googleads-mobile-android-mediation#374]
Unity `2021.1.27f1`
Android `compileSdkVersion 30`

A dependency of the facebook mediation bindings causes `androidx.work.work-runtime-2.7.0` to be imported which relies on SDK 31 to compile. In a project targeting SDK 30 this results in the following error during building.

```
Execution failed for task ':launcher:checkDebugAarMetadata'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
   > The minCompileSdk (31) specified in a
     dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
     is greater than this module's compileSdkVersion (android-30).
     Dependency: :androidx.work.work-runtime-2.7.0:.
     AAR metadata file: /Users/mdabiri/.gradle/caches/transforms-2/files-2.1/a09535bbb1b243123bd241f205ac3683/jetified-androidx.work.work-runtime-2.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by bearhugmo** [comment]
Issue also occurs if using `com.google.android.gms:play-services-ads:20.2.`

**Comment by ewnu** [comment]
if your app needs more time to upgrade to 31,
you can bump the compileSdkVersion version to 31, yet staying 30 on targetSdkVersion
other workaround would be making a separate module.
That way, you can keep other code base on 30, and use 31(or 32 if you want) on a new module.

**Comment by joshh-devrel** [comment]
You can find the latest Meta Unity adapter version [here](https://developers.google.com/admob/unity/mediation/meta#meta-audience-network-unity-mediation-plugin-changelog) and the Android adapter's `compileSdkVersion` [here](https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/meta/meta/build.gradle#L23).
