### ISSUE TITLE
Applovin adapter apparent bug on loading rewarded videos

### ISSUE THREAD

**Issue by ShmulikArmon** [googleads/googleads-mobile-android-mediation#376]
Hey,

We are using Admob 20.5.0 and adapter version 10.3.4.0 (latest atm)

We are seeing the following exception consistently in the logs - 
...
2021-11-25 15:47:33.715 25091-25091/? E/Ads: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.applovin.adview.AppLovinIncentivizedInterstitial.preload(com.applovin.sdk.AppLovinAdLoadListener)' on a null object reference
        at com.google.ads.mediation.applovin.AppLovinMediationAdapter.loadRewardedAd(AppLovinMediationAdapter.java:292)
...

Looking at the line it originates it, it appears to be a bug... 

https://github.com/googleads/googleads-mobile-android-mediation/blob/33df7fa3b1db6fc26b2a79f4675ed230b4b1cbfb/ThirdPartyAdapters/applovin/applovin/src/main/java/com/google/ads/mediation/applovin/AppLovinMediationAdapter.java#L292

As you can see mIncentivizedInterstitial is referenced directly while it is only initiated in a separate thread - 

https://github.com/googleads/googleads-mobile-android-mediation/blob/33df7fa3b1db6fc26b2a79f4675ed230b4b1cbfb/ThirdPartyAdapters/applovin/applovin/src/main/java/com/google/ads/mediation/applovin/AppLovinMediationAdapter.java#L279

This code has existed for 6 months so I'm not sure its the reason we are not seeing any ads from applovin, but I can't find a different reason for it at the moment... am I missing something? thanks

**Comment by joshh-devrel** [comment]
@ShmulikArmon Please update to use the latest [AppLovin Android adapter](https://developers.google.com/admob/android/mediation/applovin#applovin-android-mediation-adapter-changelog) version.
