### ISSUE TITLE
When Nend logo image Url is null , crash app. 

### ISSUE THREAD

**Issue by kkkkan** [googleads/googleads-mobile-android-mediation#379]
Hey,

nend's neitive ad sometimes  logo image url is null. But [NendAdLoader](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NativeAdLoader.java) suppose that situations , so app crashes by NullPointerException by Uri#parse.
( 
environment is 
- com.google.ads.mediation:nend:8.0.1.0
- com.google.android.gms:play-services-ads:20.4.0
- net.nend.android:nend-sdk:8.0.1
)

So, I think [https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NativeAdLoader.java) Line 127 -130](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NativeAdLoader.java#L127-L130) should change

```
    NendNativeMappedImage logoImage = null;
    if (shouldReturnUrlsForImageAssets || nendLogoImage != null) {
      logoImage = new NendNativeMappedImage(context, nendAdImage, Uri.parse(ad.getLogoImageUrl()));
    }
```
 to 

```
     NendNativeMappedImage logoImage = null;

    // add following lines
    String logoUrlStr = ad.getLogoImageUrl();
    Uri logoUri;
    if (logoUrlStr != null && !logoUrlStr.isEmpty()){
      logoUri = Uri.parse(logoUrlStr);
    }else{
      logoUri = Uri.EMPTY;
    }
    // add fin

    if (shouldReturnUrlsForImageAssets || nendLogoImage != null) {
      // change following line (constructor`s 3rd argument)
      logoImage = new NendNativeMappedImage(context, nendLogoImage, logoUri);
    }
```

And [https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NativeAdLoader.java) Line 122 -125](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NativeAdLoader.java#L122-L125) should change

```
    NendNativeMappedImage adImage = null;
    if (shouldReturnUrlsForImageAssets || nendAdImage != null) {
      adImage = new NendNativeMappedImage(context, nendAdImage, Uri.parse(ad.getAdImageUrl()));
    }
```
 to 

```
     NendNativeMappedImage adImage = null;

    // add following lines
    String imageUrlStr = ad.getAdImageUrl();
    Uri imageUri;
    if (imageUrlStr != null && !imageUrlStr.isEmpty()){
      imageUri = Uri.parse(imageUrlStr);
    }else{
      imageUri = Uri.EMPTY;
    }
    // add fin

    if (shouldReturnUrlsForImageAssets || nendAdImage != null) {
      // change following line (constructor`s 3rd argument)
      adImage = new NendNativeMappedImage(context, nendAdImage,  imageUri));
    }
```
just in case.

Thanks.

**Comment by joshuajplagonera** [comment]
Hi @kkkkan 
Thank you for reporting this issue to us.
We have made changes to the nend Android adapter to resolve this issue. You can view the changes here: https://github.com/googleads/googleads-mobile-android-mediation/commit/72ec22370af2cc128019b4e532e3f080b54b7875
The fix should be out on the next version of the adapter.
