### ISSUE TITLE
Admob mediation with Adcolony in Unity 3D W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version. I/AdColony [INFO]: Configuring AdColony

### ISSUE THREAD

**Issue by cavallinii** [googleads/googleads-mobile-android-mediation#385]
Hi, I have an app developed with Unity and I use Admob to monetize it. I have added the open bidding mediation of AppLovin and AdColony using the adapters that Admob offers for this. I have followed the steps Adcolony has ad requests but no impressions and I get the following log:

W/AdColonyMediationAdapter: Unexpected SDK version format: . Returning 0.0.0 for SDK version.
I/AdColony [INFO]: Configuring AdColony

I don't know what to do and I have already contacted adcolony support and they say to add the adcolony SDK but you only need the Admob adapter to make it work because years ago the mediation worked for me.

Thanks.

**Comment by joshh-devrel** [comment]
@cavallinii Please update to use the latest [AdColony adapter](https://developers.google.com/admob/android/mediation/adcolony#adcolony-android-mediation-adapter-changelog) version.
