### ISSUE TITLE
myTarget adapter - missing sdk initialization

### ISSUE THREAD

**Issue by apshard** [googleads/googleads-mobile-android-mediation#388]
Please add explicit SDK initialization in myTarget adapter.

Right now there is a comment in the "initialize" method
//myTarget SDK does not have any API for initialization.

But in fact, SDK does have API for initialization (MyTargetManager.initSdk) and it should be called to cover the case when auto init is disabled in the manifest (by com.my.target.autoInitMode=0). So please add the following line to the "initialize" method in myTarget adapter
MyTargetManager.initSdk(context)

**Comment by joshuajplagonera** [comment]
Hi @apshard , 

Thank you for raising this concern. We have confirmed from myTarget that calling `MyTargetManager.initSdk()` is optional and should not be needed in the adapter since they automatically initialize the SDK.

**Comment by apshard** [comment]
Hi @joshuajplagonera Yes, this is optional and not needed by default when their SDK initializes automatically.
BUT it's needed in the case when we explicitly disabled auto init by adding to the manifest
`<meta-data android:name="com.my.target.autoInitMode" android:value="0"/>`
