### ISSUE TITLE
Please release an adapter so AdMob users can shows ads from AppLovin MAX

### ISSUE THREAD

**Issue by svenoaks** [googleads/googleads-mobile-android-mediation#397]
[Adapter exists for AppDiscovery](https://developers.google.com/admob/android/mediation/applovin) but not for MAX.

**Comment by joshh-devrel** [comment]
This is WAI. MAX is the mediation product/platform for AppLovin to serve third-party ads, while the Google's AppLovin adapter is another way around that serves AppLovin ads.
