### ISSUE TITLE
MediationCustomEvent-could not call remote method

### ISSUE THREAD

**Issue by GenarC** [googleads/googleads-mobile-android-mediation#398]
We add Huawei Ads to waterfall as mediaiton - Custom Event. For interstitial ads, we are having problems to call FullScreenContentCallback methods. We are calling CustomEventInterstitialListener functions, however these methods are not calling FullScreenContentCallback methods %95 of the time. When I track the method call, it reaches "could not call remote method"

`
interstitialAd.fullScreenContentCallback = object :
FullScreenContentCallback() {
override fun onAdFailedToShowFullScreenContent(error: AdError) {
Log.d("HuaweiCustomEventInterstitialEventForwarder-admob", "onAdFailedToShowFullScreenContent");
}

override fun onAdImpression() {
Log.d("HuaweiCustomEventInterstitialEventForwarder-admob", "onAdImpression");
}

override fun onAdShowedFullScreenContent() {
Log.d("HuaweiCustomEventInterstitialEventForwarder-admob", "onAdShowedFullScreenContent");
}

// override fun onAdClicked() {
// Log.d("HuaweiCustomEventInterstitialEventForwarder-admob", "onAdClicked");
// }

override fun onAdDismissedFullScreenContent() {
Log.d("HuaweiCustomEventInterstitialEventForwarder-admob", "onAdDismissedFullScreenContent");
}
}
`

**Comment by joshh-devrel** [comment]
Closed as the issue wasn't reproducible.

@GenarC Feel free to re-open if the issue still persists and it would be helpful if you can provide a sample project that can reproduce it.
