### ISSUE TITLE
False Mediation Suite Report

### ISSUE THREAD

**Issue by VineshChauhan24** [googleads/googleads-mobile-android-mediation#399]
When we Implement FB mediation With Admob and Use Test Ids [https://developers.google.com/admob/android/test-ads](mentiond here) , and use Mediation Suite to Test Our Ads Place and Integration. Mediation Suite Marked All Ids as rewarded Ads. so will it be safe to use Live ads id. We are worried to use live ads id due to Admob's Strict Double Policy.
 i have used 

```
//    admob
    implementation 'com.google.android.gms:play-services-ads:20.4.0'
    //facebook mediation
    implementation 'com.google.ads.mediation:facebook:6.8.0.0'
```

![IMG_20220423_154843](https://user-images.githubusercontent.com/31922443/164890478-324c8b75-28e0-44a3-b59f-8ca381f254ae.jpg)
![IMG_20220423_154833](https://user-images.githubusercontent.com/31922443/164890483-3570a183-10c6-47ab-962f-ee4365f8e854.jpg)

**Comment by joshh-devrel** [comment]
@VineshChauhan24 Mediation Test Suite is already sunset, please use [ad inspector](https://developers.google.com/admob/android/ad-inspector) for your on-device debugging needs.
