### ISSUE TITLE
Admob limitation effects other bidding partners

### ISSUE THREAD

**Issue by BurkPow** [googleads/googleads-mobile-android-mediation#406]
When we have ad serving limit on admob account, it also effects other mediation partners like facebook audience network. However Admob says " limited ad serving applies to AdMob Network only and doesn't affect third-party mediation, house ads, and direct sold campaign." We are not getting impressions from other networks when admob is on limit

**Comment by ericleich** [comment]
Limited ad serving, does not impact waterfall mediation, but I've confirmed does impact bidding integrations. Since Meta (Facebook) audience network is currently bidding only. I've requested that https://support.google.com/admob/answer/9493252 gets updated to clarify this.

**Comment by Mouadabdelghafouraitali** [comment]
The real question here is why AdMob keeps putting the ad limit in our account for **NO REASON**, I used to use AdMob since 2017, and I've never faced any issue, but in 2020, AdMob start putting the ad limit in my account from time to time, very fracturing :/
