### ISSUE TITLE
Pangle/ByteDance adapter will support Native ads bidding?

### ISSUE THREAD

**Issue by Luklek** [googleads/googleads-mobile-android-mediation#407]
Why the adapter doesn't support Native Ads too? (they are available as waterfall with Pangle own admob adapter and as bidding in Applovin Max already)

**Comment by joshh-devrel** [comment]
As noted in https://developers.google.com/admob/android/mediation/pangle#supported_integrations_and_ad_formats, Pangle adapter version `4.5.0.6.1` or higher supports native ads, where using the latest version is recommended.
