### ISSUE TITLE
Fyber Adapter - muteVideo param not handled

### ISSUE THREAD

**Issue by thomasdorey** [googleads/googleads-mobile-android-mediation#417]
Can you update the Fyber Adapter to handle the muteVideo param that allows to mute video ads.

See fyber doc here : https://developer.fyber.com/hc/en-us/articles/360019744297-Android-Ad-Formats

**Comment by joshh-devrel** [comment]
We now support passing the `muteVideo` param, see [DT Exchange integration doc](https://developers.google.com/admob/android/mediation/dt-exchange#network-specific_parameters).
