### ISSUE TITLE
New release of MoPub adapter

### ISSUE THREAD

**Issue by cnordvik** [googleads/googleads-mobile-android-mediation#42]
Is it possible that you can release a version of MoPub with this fix? 
https://github.com/googleads/googleads-mobile-android-mediation/pull/41

Since it crashes quite often in production it would be very nice with a new build of the MoPub adapter.

**Comment by shankervennam** [comment]
We released these changes in version [4.19.0.1](https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.mopub/4.19.0.1).
