### ISSUE TITLE
Transitioning from CustomEventBanner to Adapter missing onDestroy

### ISSUE THREAD

**Issue by sanderson82** [googleads/googleads-mobile-android-mediation#428]
We have a CustomEventBanner we are trying to convert to Adapter.  Transitioning to Adapter there is no method for when the view is destroyed or no longer in use.  eg. The onDestroy method in CustomEventBanner.  Since we do not know when the banner is no longer in use, too many references are held and it's causing a memory leak in our application.

What does AdMob recommend for this scenario?  I would like to clean up references on unused views as early as possible.

**Comment by htteng1976** [comment]
We're also facing this issue. Any update?

**Comment by htteng1976** [comment]
Hi @sanderson82 ,

I tried to implement the interface MediationAdapter on Adapter and its depredated method onDestroy() still working when AdManagerAdView.destroy() is called.

In Kotlin,
`
class MyBannerAdapter: Adapter(), MediationAdapter {
    override fun onDestroy() {
        // detect the AdManagerAdView is destroyed
    }
}
`

The official document didn't metion this part but hopes it works for you.
https://developers.google.com/ad-manager/mobile-ads-sdk/android/custom-events/banner#request_a_banner_ad

Best regards,
Brandon

**Comment by joshh-devrel** [comment]
Thanks @htteng1976 for attaching the documentation. 

@sanderson82 I am going to close this issue, please feel free to re-open it if needed.
