### ISSUE TITLE
Chartboost Adapter: error codes in code and in documentation don't match

### ISSUE THREAD

**Issue by robeekhout** [googleads/googleads-mobile-android-mediation#429]
Hi AdMob team,

The adapter for Chartboost defines some error codes here: https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/chartboost/chartboost/src/main/java/com/google/ads/mediation/chartboost/ChartboostMediationAdapter.java#L46 

However, these don't correspond with the error codes in the AdMob documentation for the Chartboost adapter: https://developers.google.com/ad-manager/mobile-ads-sdk/android/mediation/chartboost#error_codes 

Example: 
Code says:   static final int ERROR_AD_ALREADY_LOADED = **101**;
Helpsite says: **101** | The requested ad size does not match a Chartboost supported banner size.

I believe the error codes in the code are correct, so the request would be to update the developers.google.com website to correspond with the error codes in the code.

Please let me know if more info is needed.

Kind regards,

Rob Eekhout
Solutions Engineer at Chartboost

**Comment by joshuajplagonera** [comment]
Hi @robeekhout 

The adapter link you provided is in the incorrect branch. Please note that we are now using the `main` branch for the latest updates.
See: https://github.com/googleads/googleads-mobile-android-mediation/blob/main/ThirdPartyAdapters/chartboost/chartboost/src/main/java/com/google/ads/mediation/chartboost/ChartboostConstants.java#L39
