### ISSUE TITLE
CustomEvent initialization missing ageRestrictedUser information

### ISSUE THREAD

**Issue by sanderson82** [googleads/googleads-mobile-android-mediation#436]
The initialize method gets called for custom events, but there is no way to determine whether the user is an age restricted user.

The logs here indicate it is not called.  
https://github.com/googleads/googleads-mobile-android-mediation/blob/master/Example/customevent/src/main/java/com/google/ads/mediation/sample/customevent/SampleCustomEvent.java#L115

So, is it available or not?  If so, how can we get age restricted user from it?

**Comment by joshh-devrel** [comment]
@sanderson82 
The app itself should have its own way to collect the information of whether the user is an age restricted user, for example through a form (see [example](https://github.com/googleads/googleads-mobile-android-examples/blob/main/java/advanced/APIDemo/app/src/main/java/com/google/android/gms/example/apidemo/AdMobAdTargetingFragment.java)). Then, pass that information to the third-party SDK using their APIs or following their dev doc instructions, where when that should be set depends on the SDK behaviors.
