### ISSUE TITLE
[mingegral]The banner ad size from Mintegral is very small. 

### ISSUE THREAD

**Issue by tongledi** [googleads/googleads-mobile-android-mediation#459]
I am using the AdMob Unity 7.4.1 SDK and the Mintegral 1.1.0 adapter in my game. The banner ad size from Mintegral is very small. We have tested both AdMob's adaptive banner and fixed size options, but the results are the same - the banner is still very small.Google, Unity, Pangle, Fyber, and other banner ads have normal sizes.

**Comment by joshh-devrel** [comment]
This issue is fixed in PR #461.
