### ISSUE TITLE
Getting error code 3 - "Unable to instantiate mediation adapter class" when using Facebook ads in Admob mediation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googleads/googleads-mobile-android-mediation#469]
I use these dependencies on an app that I work on, for banner ads (AdView) and native ads:

```
    implementation 'com.google.android.gms:play-services-ads:22.1.0'
    implementation 'com.facebook.android:audience-network-sdk:6.14.0'
    implementation 'com.google.ads.mediation:facebook:6.14.0.0'
```

This is the only thing that's mentioned that's needed in the app for mediation of Admob to include Facebook ads:
https://developers.google.com/admob/android/mediate
https://developers.google.com/admob/android/mediation/meta
https://developers.facebook.com/docs/audience-network/bidding/partner-mediation/admob/

We tried all kinds of ads configurations on Facebook website, and we tried on Admob website too, to have either "billing" or "waterfall" being set. We also tried to make it use test-ads.

And still, all I get is this error when it tries to reach Facebook:

error code 3 - "Unable to instantiate mediation adapter class"

Checking via the ad-inspector, it just added that it's "no fill".

Trying to print the response, I get this:

```
"Response ID": "2KOaZLefEMaJ-wbm-YGIAg",
"Mediation Adapter Class Name": "com.google.ads.mediation.admob.AdMobAdapter",
"Adapter Responses": [
  {
	"Adapter": "com.google.ads.mediation.facebook.FacebookAdapter",
	"Latency": 0,
	"Ad Source Name": "Meta Audience Network",
	"Ad Source ID": "...",
	"Ad Source Instance Name": "Meta Audience Network",
	"Ad Source Instance ID": "...",
	"Credentials": {
	  "pubid": "..."
	},
	"Ad Error": {
	  "Code": 3,
	  "Message": "Unable to instantiate mediation adapter class.",
	  "Domain": "com.google.android.gms.ads",
	  "Cause": "null"
	}
  },
```

How could it be?
Isn't there any way to at least try out a sample test ad, just as we have ad-units for various Amob ads?
What's the purpose of having 2 types of mediation, which don't seem to have a difference between them ("billing" and "waterfall")  ?

**Comment by pritampawade** [comment]
I am also facing a similar issue, test banner ads are showing properly but native ads are throwing this error.

Did you find any solution?

**Comment by NVentimiglia** [comment]
Thanks for the report, let me take a look at get back to you.

**Comment by stevenhaggerty** [comment]
I get this too. Any news?

Deps:
    implementation 'com.google.android.gms:play-services-ads:22.4.0'
    implementation 'com.google.ads.mediation:facebook:6.16.0.0'
    implementation 'com.facebook.android:audience-network-sdk:6.16.0'



Admob banner failed to load{
                                                                                                      "Code": 3,
                                                                                                      "Message": "Unable to instantiate mediation adapter class.",
                                                                                                      "Domain": "com.google.android.gms.ads",
                                                                                                      "Cause": "null",
                                                                                                      "Response Info": {
                                                                                                        "Response ID": "xxx",
                                                                                                        "Mediation Adapter Class Name": "",
                                                                                                        "Adapter Responses": [
                                                                                                          {
                                                                                                            "Adapter": "com.google.ads.mediation.facebook.FacebookAdapter",
                                                                                                            "Latency": 1,
                                                                                                            "Ad Source Name": "Meta Audience Network",
                                                                                                            "Ad Source ID": "xxx",
                                                                                                            "Ad Source Instance Name": "Facebook Audience Network",
                                                                                                            "Ad Source Instance ID": "xxx",
                                                                                                            "Credentials": {
                                                                                                              "pubid": "xxx"
                                                                                                            },
                                                                                                            "Ad Error": {
                                                                                                              "Code": 3,
                                                                                                              "Message": "Unable to instantiate mediation adapter class.",
                                                                                                              "Domain": "com.google.android.gms.ads",
                                                                                                              "Cause": "null"
                                                                                                            }
                                                                                                          }
                                                                                                        ],
                                                                                                        "Response Extras": {
                                                                                                          "mediation_group_name": "xxx"
                                                                                                        }
                                                                                                      }
                                                                                                    }

**Comment by AndroidDeveloperLB** [comment]
Just to make sure, verify you have this:

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="@string/ad_mob_app_id" />

**Comment by stevenhaggerty** [comment]
Yes, it's in the android manifest. 

I eventually get admob ads, so it's all rigged up correctly.

**Comment by joshh-devrel** [comment]
@AndroidDeveloperLB
Thanks for raising the issue.

Can you confirm if the issue is resolved after you include the AdMob app ID in the manifest file? If not, please provide the full stacktrace or logging that indicates why the Meta adapter failed to initiate.

**Comment by joshh-devrel** [comment]
Closed due to inactivity.
