### ISSUE TITLE
Time Out Duration of Unity Mediation Adapter is Excessively Long

### ISSUE THREAD

**Issue by mobile94ever** [googleads/googleads-mobile-android-mediation#473]
In case of slow or no connection, Unity adapter takes very long to initialize ~8 seconds. All the other adapters like vungle, pangle, ironsource initializes without the need for internet or they just simply don't get initialized if no internet is detected. This increases the `MobileAds.Initiazlie()` time by a lot.
   Based on the attached log, it is evident that the Unity adapter is the only one experiencing a timeout issue. Once the Unity adapter is removed, the problem no longer occurs.
<br>
<br>
![Log](https://github.com/googleads/googleads-mobile-android-mediation/assets/45561357/b49a68f1-9804-4f7d-9058-665a61600f40)

**Comment by joshh-devrel** [comment]
@mobile94ever Can you provide the complete logging that might show the error messages for Unity Ads SDK initialization if there are any? Also, is this reproducible in [our Android examples](https://github.com/googleads/googleads-mobile-android-examples)?

**Comment by joshh-devrel** [comment]
Closed this issue as it wasn't reproducible on our end and there isn't enough information to proceed.

@mobile94ever Please feel free to re-open this issue if you can provide the complete logging/ stack trace, reproducing steps and sample project that can reproduce the issue.

**Comment by FeliceCasa** [comment]
We’ve observed a similar issue in our app. According to our Firebase tracking, about 10% of users encounter Unity Ads adapter initialization failures when opening the app, and around 3% of users experience the same with the ironSource adapter.
