### ISSUE TITLE
InMobi adapter is not relaying onAdDisplayFailed event

### ISSUE THREAD

**Issue by sandeep5193** [googleads/googleads-mobile-android-mediation#477]
we get below message in the logcat but `onAdFailedToShowFullScreenContent()` method is not getting called: 

`{
                                                                                                      "Code": 106,
                                                                                                      "Message": "InMobi SDK failed to display an interstitial ad.",
                                                                                                      "Domain": "com.google.ads.mediation.inmobi",
                                                                                                      "Cause": "null"
                                                                                                    }`

**Comment by joshh-devrel** [comment]
Thanks @sandeep5193 for raising this issue, we are currently working on the fix.

**Comment by thanvirm** [comment]
This got fixed by https://github.com/googleads/googleads-mobile-android-mediation/commit/561afb084e47682837919c57bdc01a41d9be5780.
