### ISSUE TITLE
Publish updated AdColony adapter on Bintray

### ISSUE THREAD

**Issue by akwkong** [googleads/googleads-mobile-android-mediation#49]
Would it be possible to publish an updated AdColony adapter to Bintray containing the fixes from this pull request?
https://github.com/googleads/googleads-mobile-android-mediation/pull/45

We have some publishers that are waiting on those fixes. Thanks!

**Comment by sbagadi** [comment]
The AdColony adapter with the changes from PR https://github.com/googleads/googleads-mobile-android-mediation/pull/45 is now published on Bintray as version [3.3.0.1](https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.adcolony/3.3.0.1)

**Comment by akwkong** [comment]
Thanks sbagadi!
