### ISSUE TITLE
Hardcoding of MoPub keywords

### ISSUE THREAD

**Issue by scudza** [googleads/googleads-mobile-android-mediation#51]
Hi
I noticed in `MopubAdapter.java` line 296 and 231 from the keywords that are passed in only the gender and age are passed on to the ads request. Is this intended behaviour? In our implementation we require that our ads keywords are passed on to the request for both native and banner ads. How would we accomplish this using the mopub adapter?

**Comment by shankervennam** [comment]
Please follow [this](https://developers.google.com/admob/android/targeting#gender) steps to send gender and age information along with AdRequest.
