### ISSUE TITLE
Unable to instantiate mediation adapter class.

### ISSUE THREAD

**Issue by TonyAnine** [googleads/googleads-mobile-android-mediation#519]
onAdFailedToLoad:{
                                                                                                      "Code": 3,
                                                                                                      "Message": "Unable to instantiate mediation adapter class.",
                                                                                                      "Domain": "com.google.android.gms.ads",
                                                                                                      "Cause": "null",
                                                                                                      "Response Info": {
                                                                                                        "Response ID": "XXX",
                                                                                                        "Mediation Adapter Class Name": "",
                                                                                                        "Adapter Responses": [
                                                                                                          {
                                                                                                            "Adapter": "com.google.ads.mediation.facebook.FacebookAdapter",
                                                                                                            "Latency": 0,
                                                                                                            "Ad Source Name": "Meta Audience Network",
                                                                                                            "Ad Source ID": "XXX",
                                                                                                            "Ad Source Instance Name": "Meta Audience Network",
                                                                                                            "Ad Source Instance ID": "XXX",
                                                                                                            "Credentials": {
                                                                                                              "pubid": "XXX"
                                                                                                            },
                                                                                                            "Ad Error": {
                                                                                                              "Code": 3,
                                                                                                              "Message": "Unable to instantiate mediation adapter class.",
                                                                                                              "Domain": "com.google.android.gms.ads",
                                                                                                              "Cause": "null"
                                                                                                            }
                                                                                                          }
                                                                                                        ],
                                                                                                        "Response Extras": {
                                                                                                          "mediation_group_name": "XXX"
                                                                                                        }
                                                                                                      }
                                                                                                    }

**Comment by thanvirm** [comment]
Hey,

Are you trying to use Meta Audience Network in a waterfall mediation chain? Waterfall is no longer supported for Meta Audience Network. Please see https://developers.google.com/admob/android/mediation/meta for how to integrate Meta Audience Network for mediation. Thanks!

**Comment by TonyAnine** [comment]
Yes, I used waterfall mediation ads. Do I need to remove this?

**Comment by thanvirm** [comment]
Yes.

**Comment by TonyAnine** [comment]
The problem has been solved, thank you very much.
