### ISSUE TITLE
Facebook Native ad mediation can not click

### ISSUE THREAD

**Issue by ParkSangGwon** [googleads/googleads-mobile-android-mediation#75]
When I use `UnifiedNativeAd` for facebook medation, advertise's click did not work.
I think this code not consider about `UnifiedNativeAdView`.
https://github.com/googleads/googleads-mobile-android-mediation/blob/b210a834efc2f29ecdec95b642ca810e0c896eaa/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java#L909

This code handle only `NativeAppInstallAdView`.
This code have to change handling `NativeAppInstallAdView` and `UnifiedNativeAdView`.
Now I back to old native advertise(`NativeAppInstallAdView`, `NativeContentAdView`).
Please fix this code.

**Comment by spilaka** [comment]
Fixed issue.
