### ISSUE TITLE
Vungle Adapter 6.2.5.0 and Vungle SDK 6.2.5+ are not getting Test Ads

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-android-mediation#79]
I've checked 5.3 version of SDK+Adapter and they've worked fine with my AdmobAdUnits. I'm setting vungle placementID for adrequest in GAD.
After compiling latest vungle adapter from this repo I couldn't get ads I used to see with vungle 5.3.

Also I wonder what for do we need to set the placementID separately if it can be taken from Admob console (server params)? 

I've tried setting placementID as array item in allPlacements at the begining of AdapterParametersParser.parse method and everything worked fine. Though it is used later for loading ad. But in case when networkExtras (mediationExtras) are null adapter throws exception and does not let us continue working with server params only.

Here is a code I used (sure there is a better way of doing that I've done, but it was only for debug).

```javascript
public static Config parse(Bundle networkExtras, Bundle serverParameters) throws IllegalArgumentException {
        String[] placements = null;
        if (networkExtras != null) {
            placements = networkExtras.getStringArray(VungleExtrasBuilder.EXTRA_ALL_PLACEMENTS);
        }

        //setting placementID as allPlacements item (PLAYING_PLACEMENT from Admob console)
        if (serverParameters.containsKey(VungleManager.PLAYING_PLACEMENT)){
            String pl = serverParameters.getString(VungleManager.PLAYING_PLACEMENT);
            if (placements == null || placements.length == 0) {
                if (pl != null && pl.length()>0){
                    placements = new String[]{ pl };
                }
            } else {
                boolean found = false;
                for (int i = 0; i< placements.length; i++) {
                    if (placements[i] == pl){
                        found = true;
                        break;
                    }
                }
                if (!found){
                    String [] tmp = new String[placements.length+1];
                    for (int i = 0; i< placements.length; i++) {
                        tmp[i] = placements[i];
                    }
                    tmp[tmp.length-1] = pl;
                    placements = tmp;
                }
            }
        }
```

**Comment by rchallenger** [comment]
Small update to issue:
<details> 
  <summary>Here is a log for ad request using VungleMediationExtras and unchanged adapter code (latest version)</summary>
05-25 11:20:25.084: I/Unity(26157): SetAdmobParams for Vungle_c2
05-25 11:20:25.084: I/Unity(26157):  
05-25 11:20:25.084: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.091: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider Initializing with ads_enabled=True, tagged_for_children=True, is_designed_for_families=False, non_personalized=False
05-25 11:20:25.091: I/Unity(26157):  
05-25 11:20:25.091: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.093: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider Processing params: count = 3
05-25 11:20:25.093: I/Unity(26157): GOOGLEADS_BANNER_ID : ca-app-pub-3940256099942544/6300978111
05-25 11:20:25.093: I/Unity(26157): GOOGLEADS_INTERSTITIAL_ID : ca-app-pub-4698438002143937/6621853212
05-25 11:20:25.093: I/Unity(26157): GOOGLEADS_VUNGLE_PLACEMENT_ID_INTERSTITIAL : DEFAULT44421
05-25 11:20:25.093: I/Unity(26157):  
05-25 11:20:25.093: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.093: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider vungle_placement_interstitial_id initialized
05-25 11:20:25.093: I/Unity(26157):  
05-25 11:20:25.093: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.094: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider banner initialized
05-25 11:20:25.094: I/Unity(26157):  
05-25 11:20:25.094: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.098: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider Requesting banner
05-25 11:20:25.098: I/Unity(26157):  
05-25 11:20:25.098: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.144: D/AdsUnity(26157): Calling loadAd() on Android
05-25 11:20:25.146: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider interstitial initialized
05-25 11:20:25.146: I/Unity(26157):  
05-25 11:20:25.146: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.150: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider Requesting interstitial
05-25 11:20:25.150: I/Unity(26157):  
05-25 11:20:25.150: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:25.152: D/DynamitePackage(26157): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
05-25 11:20:25.157: I/Ads(26157): Starting ad request.
05-25 11:20:25.157: I/Ads(26157): Use AdRequest.Builder.addTestDevice("F98CD41FB43C8D90056861BE22446740") to get test ads on this device.
05-25 11:20:25.166: D/AdsUnity(26157): Calling hide() on Android
05-25 11:20:25.185: D/DynamitePackage(26157): Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
05-25 11:20:25.188: I/Ads(26157): Starting ad request.
05-25 11:20:25.189: I/Ads(26157): Use AdRequest.Builder.addTestDevice("F98CD41FB43C8D90056861BE22446740") to get test ads on this device.
05-25 11:20:25.191: W/Ads(23969): App does not have the required permissions to get location
05-25 11:20:25.193: W/Ads(26157): Not retrying to fetch app settings
05-25 11:20:25.198: I/AsyncOpDispatcher(23952): 19-GetRecentContext
05-25 11:20:25.201: V/ConnectivityManager(23969): isActiveNetworkMetered() returns:false
05-25 11:20:25.253: W/Ads(23969): App does not have the required permissions to get location
05-25 11:20:25.258: I/AsyncOpDispatcher(23952): 19-GetRecentContext
05-25 11:20:25.262: I/SFPerfTracer(643):      triggers: (rate: 1628:242393) (compose: 2:173) (post: 8:5118) (render: 2:2438) (115:1773301 frames) (116:1975823)
05-25 11:20:25.262: D/SFPerfTracer(643):        layers: (1:9) (StatusBar (0xac5ef800): 3:407808)* (com.android.systemui.ImageWallpaper (0xacac3400): 0:244665)* (DimLayerController/Stack=0 (0xac5f0c00): 0:7892)* (animation background stackId=1 (0xac5ee400): 0:1758)* (Sprite (0xac5ebc00): 0:421)* (NavigationBar (0xab129c00): 0:1961)* (com.PSVGamestudio.BrandNewPrototype/com.unity3d.player.UnityPlayerActivity (0xab127400): 0:104)* (SurfaceView - com.PSVGamestudio.BrandNewPrototype/com.unity3d.player.UnityPlayerActivity (0xacac2000): 0:101)* (SurfaceView - com.PSVGamestudio.BrandNewPrototype/com.unity3d.player.UnityPlayerActivity (0xac5ed000): 116:470) 
05-25 11:20:25.269: V/ConnectivityManager(23969): isActiveNetworkMetered() returns:false
05-25 11:20:25.429: I/SFPerfTracer(643):      triggers: (rate: 52:1442) (2721317 sw vsyncs) (0 skipped) (356:2499752 vsyncs) (358:5512071)
05-25 11:20:25.438: I/Ads(26157): Trying mediation network: https://googleads.g.doubleclick.net/aclk?sa=L&ai=CSZDmRscHW5PqFIe4YNm6qvAL-cnapgXR74W6kgEAEAggyd3IRGClxqSGrCOpAgAAAACAhC5BqAMBqgQgT9D7pD2MfIIMYPLo_kMAzT9wRdgjLCOBygc_p4VxruKQBgHABguAB4H4qTCYBwHSCAkIguGQYBABGAI&num=1&cid=CAASBORoXdE&sig=AOD64_0jWakxx1IWaQvvjuN__laGP5UAOA&adurl=http://example.com
05-25 11:20:25.440: I/Ads(26157): Instantiating mediation adapter: com.vungle.mediation.VungleInterstitialAdapter
05-25 11:20:25.453: W/Ads(26157): Server parameters: {"appid":"59f2dc9463f1408b3e006122","gwhirl_share_location":"1","placementID":"DEFAULT44421"}
05-25 11:20:25.505: D/VungleApiClient(26157): Location permission was not granted, location information will not be included
05-25 11:20:25.518: V/Vungle(26157): +--vungle/
05-25 11:20:25.522: V/ConnectivityManager(26157): isActiveNetworkMetered() returns:false
05-25 11:20:25.541: D/OkHttp(26157): --> POST https://ads.api.vungle.com/config http/1.1
05-25 11:20:25.541: D/OkHttp(26157): Content-Type: application/json
05-25 11:20:25.541: D/OkHttp(26157): Content-Length: 1147
05-25 11:20:25.541: D/OkHttp(26157): Vungle-Version: 5.1.0
05-25 11:20:25.541: D/OkHttp(26157): {"device":{"make":"motorola","model":"XT1635-02","osv":"7.1.1","carrier":"Vodafone UA","os":"android","w":1080,"h":1776,"ext":{"vungle":{"android":{"battery_level":0.74,"battery_state":"BATTERY_PLUGGED_USB","battery_saver_enabled":0,"connection_type":"WIFI","connection_type_detail":"WIFI","data_saver_status":"NOT_APPLICABLE","network_metered":0,"locale":"ru_RU","language":"ru","time_zone":"Europe/Kiev","volume_level":1.0,"sound_enabled":1,"storage_bytes_available":8170819584,"is_tv":false,"os_api_level":25,"is_sideload_enabled":true,"sd_card_available":1,"os_name":"motorola/addison/addison:7.1.1/NPNS26.118-22-2-17/21:user/release-keys","vduid":""}}},"ua":"Mozilla/5.0 (Linux; Android 7.1.1; XT1635-02 Build/NPNS26.118-22-2-17; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36","ifa":"2f3191f1154e246","lmt":0},"app":{"id":"59f2dc9463f1408b3e006122","bundle":"com.PSVGamestudio.BrandNewPrototype","ver":"2.0.1"},"user":{"gdpr":{"consent_status":"opted_out","consent_source":"publisher","consent_timestamp":1527156180}},"request":{"placements":["DEFAULT44421"],"is_auto_cached_enforced":true}}
05-25 11:20:25.542: D/OkHttp(26157): --> END POST (1147-byte body)
05-25 11:20:26.213: D/OkHttp(26157): <-- 200 OK https://ads.api.vungle.com/config (671ms)
05-25 11:20:26.213: D/OkHttp(26157): Content-Type: application/json
05-25 11:20:26.213: D/OkHttp(26157): Vungle-Build-Rev: d3a364f6633e70db863602466bc955f1dfbf113e
05-25 11:20:26.213: D/OkHttp(26157): Vary: Accept-Encoding
05-25 11:20:26.213: D/OkHttp(26157): Date: Fri, 25 May 2018 08:20:23 GMT
05-25 11:20:26.214: D/OkHttp(26157): Connection: keep-alive
05-25 11:20:26.216: D/OkHttp(26157): {"endpoints":{"new":"https://api.vungle.com/api/v5/new","ads":"https://api.vungle.com/api/v5/test_ads","will_play_ad":"https://api.vungle.com/api/v5/will_play_ad","report_ad":"https://api.vungle.com/api/v5/report_ad","log":"https://logs.api.vungle.com/sdk","ri":"https://events.api.vungle.com/api/v5/ri"},"placements":[{"id":"59f2dc9763f1408b3e006222","reference_id":"DEFAULT44421","is_auto_cached":true,"is_incentivized":false,"supported_template_types":["fullscreen","fullscreen"],"supported_ad_formats":["vungle_local","vungle_mraid","third_party"]}],"config":{"refresh_time":86400000},"will_play_ad":{"enabled":true,"request_timeout":300},"playback":{"buffer_timeout":500},"viewability":{"moat":true},"exception_reporting":true,"logging":{"enabled":false},"vduid":"","gdpr":{"is_country_data_protected":false,"consent_title":"Personalized Ads","consent_message":"Ads are personalized. Denying would disable it","button_accept":"Accept","button_deny":"Deny"},"ri":{"enabled":false},"attribution_reporting":{"should_transmit_imei":false}}
05-25 11:20:26.216: D/OkHttp(26157): <-- END HTTP (1040-byte body)
05-25 11:20:26.354: I/Choreographer(26157): Skipped 48 frames!  The application may be doing too much work on its main thread.
05-25 11:20:26.359: D/VungleApiClient(26157): Config Response: {"endpoints":{"new":"https://api.vungle.com/api/v5/new","ads":"https://api.vungle.com/api/v5/test_ads","will_play_ad":"https://api.vungle.com/api/v5/will_play_ad","report_ad":"https://api.vungle.com/api/v5/report_ad","log":"https://logs.api.vungle.com/sdk","ri":"https://events.api.vungle.com/api/v5/ri"},"placements":[{"id":"59f2dc9763f1408b3e006222","reference_id":"DEFAULT44421","is_auto_cached":true,"is_incentivized":false,"supported_template_types":["fullscreen","fullscreen"],"supported_ad_formats":["vungle_local","vungle_mraid","third_party"]}],"config":{"refresh_time":86400000},"will_play_ad":{"enabled":true,"request_timeout":300},"playback":{"buffer_timeout":500},"viewability":{"moat":true},"exception_reporting":true,"logging":{"enabled":false},"vduid":"","gdpr":{"is_country_data_protected":false,"consent_title":"Personalized Ads","consent_message":"Ads are personalized. Denying would disable it","button_accept":"Accept","button_deny":"Deny"},"ri":{"enabled":false},"attribution_reporting":{"should_transmit_imei":false}}
05-25 11:20:26.390: I/JobManager(26157): Found pending job request{id=25, tag=reconfigJob, transient=false}, canceling
05-25 11:20:26.439: D/JobProxy24(26157): Schedule one-off jobInfo success, request{id=29, tag=reconfigJob, transient=false}, start 00:00:00 (+1 day), end 02:24:00 (+1 day) (from now), reschedule count 0
05-25 11:20:26.504: D/JobProxy24(26157): Schedule one-off jobInfo success, request{id=31, tag=cleanupJob, transient=false}, start 00:00:00, end 00:00:00 (from now), reschedule count 0
05-25 11:20:26.516: E/WifiHAL(2704): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib/liblowi_wifihal.so" not found
05-25 11:20:26.516: E/WifiHAL(2704): getLowiCallbackTable: LOWI is not supported.
05-25 11:20:26.519: E/WifiHAL(2704): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib/liblowi_wifihal.so" not found
05-25 11:20:26.520: E/WifiHAL(2704): getLowiCallbackTable: LOWI is not supported.
05-25 11:20:26.521: E/WifiHAL(2704): fetchLowiCbTableAndCapabilities: NULL lowi_handle, err: dlopen failed: library "/vendor/lib/liblowi_wifihal.so" not found
05-25 11:20:26.521: E/WifiHAL(2704): getLowiCallbackTable: LOWI is not supported.
05-25 11:20:26.543: V/VungleApiClient(26157): willPlayAd is enabled, generating a timeout client.
05-25 11:20:26.553: I/Ads(26157): Ad finished loading.
05-25 11:20:26.604: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider Banner Ad loaded, mediation adapter = 
05-25 11:20:26.604: I/Unity(26157):  
05-25 11:20:26.604: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:26.607: D/AdsUnity(26157): Calling hide() on Android
05-25 11:20:26.609: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider Banner Ad opened, mediation adapter = 
05-25 11:20:26.609: I/Unity(26157):  
05-25 11:20:26.609: I/Unity(26157): (Filename: ./artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 37)
05-25 11:20:26.616: D/PlatformAlarmService(26157): Run job, request{id=30, tag=sendReportsJob, transient=false}, waited 00:00:00, delay 00:00:00
05-25 11:20:26.622: V/ConnectivityManager(26157): isActiveNetworkMetered() returns:false
05-25 11:20:26.629: I/JobExecutor(26157): Executing request{id=30, tag=sendReportsJob, transient=false}, context PlatformAlarmService
05-25 11:20:26.632: D/Vungle(26157): SendReportsJob: Current directory snapshot
05-25 11:20:26.633: V/Vungle(26157): +--vungle/
05-25 11:20:26.633: V/Vungle(26157): |  +--DEFAULT44421.Placement
05-25 11:20:26.633: V/Vungle(26157): |  +--consentIsImportantToVungle.Cookie
05-25 11:20:26.633: V/Vungle(26157): |  +--configSettings.Cookie
05-25 11:20:26.633: V/Vungle(26157): |  +--incentivizedTextSetByPub.Cookie
05-25 11:20:26.633: I/JobExecutor(26157): Finished job{id=30, finished=true, result=SUCCESS, canceled=false, periodic=false, class=SendReportsJob, tag=sendReportsJob}
05-25 11:20:26.636: D/OkHttp(26157): --> POST https://api.vungle.com/api/v5/test_ads http/1.1
05-25 11:20:26.636: D/OkHttp(26157): Content-Type: application/json
05-25 11:20:26.636: D/OkHttp(26157): Content-Length: 1183
05-25 11:20:26.636: D/OkHttp(26157): Vungle-Version: 5.1.0
05-25 11:20:26.636: D/OkHttp(26157): User-Agent: VungleDroid/6.2.5
05-25 11:20:26.636: D/OkHttp(26157): {"device":{"make":"motorola","model":"XT1635-02","osv":"7.1.1","carrier":"Vodafone UA","os":"android","w":1080,"h":1776,"ext":{"vungle":{"android":{"gaid":"47851b7b-a70d-4fe4-8891-338861851f2e","battery_level":0.74,"battery_state":"BATTERY_PLUGGED_USB","battery_saver_enabled":0,"connection_type":"WIFI","connection_type_detail":"WIFI","data_saver_status":"NOT_APPLICABLE","network_metered":0,"locale":"ru_RU","language":"ru","time_zone":"Europe/Kiev","volume_level":1.0,"sound_enabled":1,"storage_bytes_available":8170835968,"is_tv":false,"os_api_level":25,"is_sideload_enabled":true,"sd_card_available":1,"os_name":"motorola/addison/addison:7.1.1/NPNS26.118-22-2-17/21:user/release-keys","vduid":""}}},"ua":"Mozilla/5.0 (Linux; Android 7.1.1; XT1635-02 Build/NPNS26.118-22-2-17; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36","ifa":"47851b7b-a70d-4fe4-8891-338861851f2e","lmt":0},"app":{"id":"59f2dc9463f1408b3e006122","bundle":"com.PSVGamestudio.BrandNewPrototype","ver":"2.0.1"},"user":{"gdpr":{"consent_status":"opted_out","consent_source":"publisher","consent_timestamp":1527156180}},"request":{"placements":["DEFAULT44421"]}}
05-25 11:20:26.636: D/OkHttp(26157): --> END POST (1183-byte body)
05-25 11:20:26.642: D/PlatformAlarmService(26157): Finished job, request{id=30, tag=sendReportsJob, transient=false} SUCCESS
05-25 11:20:26.650: D/PlatformAlarmService(26157): Run job, request{id=32, tag=downloadJob, transient=false}, waited 00:00:00, delay 00:00:00
05-25 11:20:26.652: D/PlatformJobService(26157): Run job, request{id=31, tag=cleanupJob, transient=false}, waited 00:00:00, start 00:00:00, end 00:00:00
05-25 11:20:26.656: I/JobExecutor(26157): Executing request{id=32, tag=downloadJob, transient=false}, context PlatformAlarmService
05-25 11:20:26.660: E/downloadJob(26157): scheduleJob: loadAd onError: 8
05-25 11:20:26.663: D/downloadJob(26157): scheduleJob: latch awaitFAILURE
05-25 11:20:26.664: I/JobExecutor(26157): Finished job{id=32, finished=true, result=FAILURE, canceled=false, periodic=false, class=DownloadJob, tag=downloadJob}
05-25 11:20:26.664: D/PlatformAlarmService(26157): Finished job, request{id=32, tag=downloadJob, transient=false} FAILURE
05-25 11:20:26.666: I/JobExecutor(26157): Executing request{id=31, tag=cleanupJob, transient=false}, context PlatformJobService
05-25 11:20:26.671: D/cleanupJob(26157): CleanupJob: Current directory snapshot
05-25 11:20:26.672: V/Vungle(26157): +--vungle/
05-25 11:20:26.672: V/Vungle(26157): |  +--DEFAULT44421.Placement
05-25 11:20:26.672: V/Vungle(26157): |  +--consentIsImportantToVungle.Cookie
05-25 11:20:26.672: V/Vungle(26157): |  +--configSettings.Cookie
05-25 11:20:26.672: V/Vungle(26157): |  +--incentivizedTextSetByPub.Cookie
05-25 11:20:26.672: V/Vungle(26157): +--vungle/
05-25 11:20:26.674: I/JobExecutor(26157): Finished job{id=31, finished=true, result=SUCCESS, canceled=false, periodic=false, class=CleanupJob, tag=cleanupJob}
05-25 11:20:26.679: D/PlatformJobService(26157): Finished job, request{id=31, tag=cleanupJob, transient=false} SUCCESS
05-25 11:20:26.781: D/BatteryService(2704): uevent={POWER_SUPPLY_TEMP=312, POWER_SUPPLY_PRESENT=1, POWER_SUPPLY_STATUS=Charging, POWER_SUPPLY_CAPACITY=74, ACTION=change, DEVPATH=/devices/soc/qpnp-smbcharger-17/power_supply/battery, SUBSYSTEM=power_supply, POWER_SUPPLY_VOLTAGE_NOW=4076209, SEQNUM=283518, POWER_SUPPLY_NAME=battery, POWER_SUPPLY_CURRENT_NOW=13275, POWER_SUPPLY_CHARGE_COUNTER=2694627, POWER_SUPPLY_CHARGE_RATE=Normal, POWER_SUPPLY_HEALTH=Good}
05-25 11:20:26.792: W/QCNEJ(3648): |CORE| CNE received unexpected action: android.intent.action.BATTERY_CHANGED
05-25 11:20:26.794: D/KeyguardUpdateMonitor(3389): received broadcast android.intent.action.BATTERY_CHANGED
05-25 11:20:26.799: D/KeyguardUpdateMonitor(3389): handleBatteryUpdate
05-25 11:20:26.851: I/art(2704): Background partial concurrent mark sweep GC freed 84061(3MB) AllocSpace objects, 40(3MB) LOS objects, 19% free, 67MB/83MB, paused 1.824ms total 192.871ms
05-25 11:20:27.004: D/OkHttp(26157): <-- 200 OK https://api.vungle.com/api/v5/test_ads (367ms)
05-25 11:20:27.004: D/OkHttp(26157): Content-Type: application/json
05-25 11:20:27.004: D/OkHttp(26157): Vary: Accept-Encoding
05-25 11:20:27.004: D/OkHttp(26157): Date: Fri, 25 May 2018 08:20:23 GMT
05-25 11:20:27.004: D/OkHttp(26157): Connection: keep-alive
05-25 11:20:27.005: D/OkHttp(26157): {"ads":[{"placement_reference_id":"DEFAULT44421","ad_markup":{"id":"5b07c747fb1565000113b033","campaign":"556725c6d03cd3b022000075|564e0f7e773796f57a00009a|ads-api-v5-testmode|5b07c747fb1565000113b034","app_id":"$0${\"app_id\":\"com.bandagames.mpuzzle.gp\",\"eventID\":\"5b07c747fb1565000113b033\"}","expiry":1529828423,"delay":0,"showClose":0,"showCloseIncentivized":0,"countdown":0,"url":"https://cdn-lb.vungle.com/zen/Vungle_30s_MagicJigsawPuzzles_151109_LiveAction_portrait_And-720x1280-Q2.mp4","videoWidth":720,"videoHeight":1280,"md5":"fake_md5","postBundle":"https://cdn-lb.vungle.com/bundles/5768689d15c3295906000119-1.zip","cta_overlay":{"enabled":false,"show_onclick":true,"time_enabled":0,"time_show":0,"click_area":1},"callToActionDest":"https://play.google.com/store/apps/details?id=com.bandagames.mpuzzle.gp","adType":"vungle_local","ad_token":"eyJjYW1wYWlnbiI6IjU1NjcyNWM2ZDAzY2QzYjAyMjAwMDA3NXw1NjRlMGY3ZTc3Mzc5NmY1N2EwMDAwOWF8YWRzLWFwaS12NS10ZXN0bW9kZXw1YjA3Yzc0N2ZiMTU2NTAwMDExM2IwMzQifQ==","requires_sideloading":false}}]}
05-25 11:20:27.006: D/OkHttp(26157): <-- END HTTP (1041-byte body)
05-25 11:20:27.026: E/Vungle(26157): Failed to download assets for DEFAULT44421. Cause:
05-25 11:20:27.026: E/Vungle(26157): com.vungle.warren.error.VungleException: No advertisements are available for your current bid. Please try again later.
05-25 11:20:27.026: E/Vungle(26157): 	at com.vungle.warren.Vungle$7.onResponse(Vungle.java:1011)
05-25 11:20:27.026: E/Vungle(26157): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
05-25 11:20:27.026: E/Vungle(26157): 	at android.os.Handler.handleCallback(Handler.java:751)
05-25 11:20:27.026: E/Vungle(26157): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-25 11:20:27.026: E/Vungle(26157): 	at android.os.Looper.loop(Looper.java:154)
05-25 11:20:27.026: E/Vungle(26157): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
05-25 11:20:27.026: E/Vungle(26157): 	at java.lang.reflect.Method.invoke(Native Method)
05-25 11:20:27.026: E/Vungle(26157): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
05-25 11:20:27.026: E/Vungle(26157): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
05-25 11:20:27.028: I/Ads(26157): No fill from any mediation ad networks.
05-25 11:20:27.030: W/Ads(26157): Failed to load ad: 3
05-25 11:20:27.082: I/Unity(26157): PSV_Prototype.ADS.GoogleAdsProvider Interstitial failed to load with message: No fill
</details>

**Comment by spilaka** [comment]
Hie are you still facing the issue ?
