### ISSUE TITLE
Facebook adapter gives Banner ad wider then it was requested

### ISSUE THREAD

**Issue by rchallenger** [googleads/googleads-mobile-android-mediation#8]
We've imported facebook-audience-sdk-4.17.0 and facebook-adapter-4.23.0.0 into demo project in Unity3D 5.3.4, play-services-10.2.0.
Through admob mediation using ad unit assigned only to Facebook ads we are able to receive facebook ads. But the banner we see is not 320px wide. In attachments it is possible to see the result of the same request using two different ad units (test admob's ids and ids, created in admob console and assigned to facebook network).

![screenshot_20170614-100024](https://user-images.githubusercontent.com/20810488/27129566-97379e98-510b-11e7-9a56-efe7eb8f5dc0.png)
![screenshot_20170614-100034](https://user-images.githubusercontent.com/20810488/27129565-973526f4-510b-11e7-926f-dc571a418593.png)

**Comment by ericleich** [comment]
What AdMob ad size are you requesting?

Here is the Facebook Audience Network [AdSize](https://developers.facebook.com/docs/reference/android/current/class/AdSize/) class. They have constants for 320x50 and then flexible width with 50, 90, or 250 height. The Facebook adapter [maps](https://github.com/googleads/googleads-mobile-android-mediation/blob/master/ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java#L418-L439) the AdMob ad size to one of these Facebook ad sizes. Depending on what ad size you're passing, it is possible that the adapter is mapping it to one of these full width formats.

**Comment by rchallenger** [comment]
Ad size requested is 320x50. No smart banners were used, only fixed size ads.

**Comment by ericleich** [comment]
Weird. You should be getting 320x50 from Facebook Audience Network then.

We'll investigate.

**Comment by ericleich** [comment]
An update on this, we still don't have a proposed fix yet for the adapter, but a workaround is to size the AdView to be explicitly 320x50 rather than wrap_content or match_parent.

**Comment by ericleich** [comment]
A fix for this was introduced in 4.25.0.0 of the Facebook adapter.
