### ISSUE TITLE
Native Ads Advanced (Unified) mediation click issue with facebook

### ISSUE THREAD

**Issue by Mateeen** [googleads/googleads-mobile-android-mediation#83]
i have successfully implemented Native Ads Advanced (Unified) in my app by following [this](https://developers.google.com/admob/android/native-unified) link but there is problem now when i turned on facebook mediation form admob everything is working fine facebook ads are loading but click listener is not working on facebook ads but it is working on google ads like click on title heading icon install button only ad showing but click listener not working on facebook native ads ad is showing but impression is not triggering video is also playing but clicks not working on facebook ads
Logs:
`05-29 12:22:40.069 31639-31639/? I/Ads: Javascript has loaded for native ads.
05-29 12:22:40.566 31639-4312/? I/Ads: Trying mediation network: https://googleads.g.doubleclick.net/aclk?sa=L&ai=Cz1yjwP8MW7SoHeLHxgKGw4uwAfnJ2qYF0e-FupIBABAIIJTTpCFgy9y0BakCAAAAAICELkGoAwGqBCpP0CSv-Fq_J9cn_5Wg96yHvJLUzzoe4J0wxHKEx1I9M7V9Y6KRDyCXXI2QBgHABguAB4H4qTCYBwHSCAcIgAEQARgC&num=1&cid=CAASBORoOaU&sig=AOD64_1NYin2FevCKXJePZBQ5-qqIPTA0A&adurl=http://example.com
05-29 12:22:40.567 31639-31639/? I/Ads: Instantiating mediation adapter: com.google.ads.mediation.facebook.FacebookAdapter
05-29 12:22:40.567 31639-31639/? W/Ads: Server parameters: {"gwhirl_share_location":"1","pubid":"855910004583223_883245********"}
05-29 12:22:41.458 31639-31639/? I/Ads: Ad finished loading.`

**Comment by spilaka** [comment]
Fixed issue.
