### ISSUE TITLE
Breaking changes in Audience Network SDK 4.99.0

### ISSUE THREAD

**Issue by minas90** [googleads/googleads-mobile-android-mediation#86]
The current mediation adapter for AN is not compatible with 4.99 version of SDK, which was released more than 2 weeks ago.

**Comment by huyduc** [comment]
Please update the adapter! FAN SDK 4.99.0 seem to fix an major crash

**Comment by JCSHoosier** [comment]
It looks like 4.99.1.0 Mediation SDK was released yesterday.

**Comment by maninomula** [comment]
Sorry for the late response. The FAN adapter 4.99.1.0 is live now.

**Comment by maninomula** [comment]
@minas90  We always try to update the adapter as soon as the new SDK version is released but in this case it was late because of some API problems. We will take your feedback and try to release them in time. Thanks.

**Comment by minas90** [comment]
@maninomula ok, I understand. Thanks for great job!
I just updated it and did the necessary code changes for FAN, it's working fine.

**Comment by maninomula** [comment]
Thanks !
