### ISSUE TITLE
Tapjoy adapter not handling home button presses properly

### ISSUE THREAD

**Issue by JCSHoosier** [googleads/googleads-mobile-android-mediation#89]
I've noticed that if I hit the home button while a Tapjoy interstitial ad is visible, upon loading up a new ad, it will not show. I do get the log message: `Show interstitial content for Tapjoy-AdMob adapter` but no ad shows. I noticed that this adapter has some criteria that could cause it to not show (vs other adapters like Facebook). 

I've been speaking with a Tapjoy rep about this and we aren't getting very far. Hopeful that someone here may have an idea!

**Comment by spilaka** [comment]
Hi Are you still facing the Issue ?

**Comment by JCSHoosier** [comment]
We weren't able to come to a resolution with a Tapjoy representative and ended up dropping the SDK recently, but yes, prior to that we were still running into this issue.

**Comment by spilaka** [comment]
Hi, I tried testing this using mediation. So, when I am trying to hit the home button when the interstitial is playing. Firstly the ad is getting paused. When again I try to open the app ,I was  able to resume the ad. The logcat doesn't show any thing like "Show interstitial content for TapJoy- AdMob adapter" . The above line only shows when the ad is displayed.

**Comment by JCSHoosier** [comment]
I can’t remember if I was able to resume the interrupted ad or not but I believe the issue was displayed in the next ad load. For instance, if you have a call to load a new ad onAdClosed, and try hitting the home button in the middle of one, no subsequent ads would show. 

If you still don’t see this occur, I will test again and let you know some more details.

**Comment by spilaka** [comment]
Hi, I tried testing  "For instance, if you have a call to load a new ad onAdClosed, and try hitting the home button in the middle of one, no subsequent ads would show." I didn't see this occur.  "Show interstitial content for TapJoy- AdMob adapter" occurs only when the ad is displayed not any other time.

**Comment by JCSHoosier** [comment]
I’ll take your word for it. Like I mentioned before, we dropped the SDK since we were having issues with it, but if we decide to bring it back on, I’ll reopen this if I notice it, but it sounds like it’s fixed now. Thanks for testing this out.

**Comment by spilaka** [comment]
Sure thing. I will close this issue. Thank you.
